/** Public, illustrative positioning. Product availability stays on the offer pages. */
export const GUARD_HOME_COPY = {
  fr: {
    navProducts: "Nos produits", navGlossary: "Les menaces cyber IA",
    eyebrow: "Monitoring & cybersécurité · Expertise française",
    title: ["Vos usages IA.", "Sous votre contrôle."],
    intro: "Des solutions françaises pour observer les usages, maîtriser les données et encadrer les actions de l’IA dans votre entreprise.",
    explore: "Explorer les usages", productsLink: "Découvrir nos produits",
    principles: ["Une approche souveraine", "Vos données, vos règles", "Une supervision au quotidien"],
    videoPause: "Mettre le fond vidéo en pause", videoPlay: "Lire le fond vidéo",
    usagesKicker: "01 / Comprendre le principe",
    usagesTitle: "Trois univers. Une même exigence.",
    usagesIntro: "Du poste de travail aux modèles, l’IA entre partout. Explorez les usages de votre entreprise et révélez les risques qui les accompagnent.",
    sceneTitle: "L’IA, à l’échelle de votre entreprise",
    sceneNote: "Schéma illustratif",
    imageAlt: "Maquette ouverte d’un bâtiment : un atelier de développement à gauche, un espace de travail collaboratif au centre, un laboratoire de modèles et de données à droite.",
    toggle: "Afficher les risques", choose: "Choisir un univers IA",
    selectHint: "Sélectionnez un espace pour l’explorer.",
    modeUsage: "Les usages", modeRisk: "Les risques", everyday: "Dans votre quotidien",
    controlsTitle: "Le rôle des contrôles", controls: "Observer · Contrôler · Tracer",
    guardRole: "Des contrôles au plus près de vos usages",
    scope: "Le schéma présente le principe. Les contrôles disponibles dépendent du produit, des intégrations et des règles configurées.",
    learnThreats: "Comprendre les menaces IA",
    universes: {
      development: {
        name: "Développement", subtitle: "Coder & automatiser", marker: "01", riskLabel: "Secrets & code vulnérable",
        daily: "Un assistant pour écrire du code, explorer un dépôt ou exécuter des tâches. Chaque prompt et chaque action peuvent exposer votre système.",
        examples: ["Assistants de code", "Agents développeurs", "Outils & automatisations"],
        risks: ["Clés, jetons ou mots de passe envoyés à l’IA.", "Code généré vulnérable ou dépendances non vérifiées.", "Actions d’un agent au-delà des droits nécessaires."],
        safeguards: ["Repérer les secrets avant l’envoi au modèle.", "Encadrer les outils et les permissions des agents.", "Tracer les décisions et faire valider les actions sensibles."],
      },
      people: {
        name: "Collaborateurs", subtitle: "Rédiger & décider", marker: "02", riskLabel: "Données sensibles exposées",
        daily: "Résumer un dossier, préparer une réunion, rédiger un document : l’IA facilite le travail quotidien, au contact d’informations parfois confidentielles.",
        examples: ["Assistants du quotidien", "Documents & synthèses", "Recherche interne"],
        risks: ["Données clients, RH ou stratégiques copiées dans un assistant.", "Services IA utilisés en dehors du cadre de l’entreprise.", "Réponses inventées prises pour des faits."],
        safeguards: ["Identifier les données sensibles dans les flux intégrés.", "Définir les services autorisés et les règles de partage.", "Garder une supervision humaine sur les décisions."],
      },
      data: {
        name: "Modèles & données", subtitle: "Entraîner & exploiter", marker: "03", riskLabel: "Corpus & modèles compromis",
        daily: "Entraîner un modèle, enrichir un assistant avec vos documents ou exploiter des données : la confiance dépend aussi des sources et des accès.",
        examples: ["Machine learning", "Bases documentaires & RAG", "Pipelines de données"],
        risks: ["Données d’entraînement ou documents de référence empoisonnés.", "Instructions malveillantes cachées dans les contenus consultés.", "Restitution d’informations à une personne non autorisée."],
        safeguards: ["Qualifier la provenance des données et les accès.", "Surveiller les échanges avec les modèles intégrés.", "Choisir l’hébergement, les destinations et la traçabilité."],
      },
    },
    productsKicker: "Nos produits", productsTitle: "Deux produits. Deux moments du risque.",
    productsIntro: "Le premier garde le poste de travail, là où le prompt part. Le second garde la passerelle, là où l’agent agit.",
    productsMeta: "Nos produits | xSOM AI Guard",
    productsDescription: "Secret Guard, l’extension qui retient les secrets avant l’envoi au modèle, et la plateforme qui encadre les actions de vos agents IA.",
    featured: "Individuelle / POC · Gratuit", extensionTag: "Le poste de travail",
    extensionTitle: "Secret Guard", extensionIntro: "Le bon réflexe, avant le prompt.",
    extensionBody: "L’extension AI Guard repère les clés, les jetons et les mots de passe dans le prompt d’un assistant pris en charge, puis suspend l’envoi. La valeur reste sur le poste : elle n’est ni affichée, ni consignée, ni transmise.",
    extensionHosts: "VS Code et Copilot, Claude Code, Codex, Windsurf Cascade.",
    extensionFeatures: ["Détection locale", "Règles explicites", "Contrôle avant l’envoi"],
    extensionAction: "Découvrir l’extension gratuite", extensionNote: "Installation locale et approbation explicite dans Codex. Parcours Entreprise administré à préparer avec xSOM.",
    extensionShotAlt: "Le panneau Secret Guard dans VS Code : état de la protection, mode d’avertissement, assistants configurés et passerelle d’entreprise.",
    extensionShotCaption: "Le panneau, tel qu’il s’ouvre depuis la barre d’état de VS Code.",
    platformTag: "La passerelle", platformTitle: "AI Guard, la plateforme",
    platformIntro: "Ce que l’agent fait, pas seulement ce qu’il dit.",
    platformBody: "La passerelle se place entre l’agent et ses outils. Chaque action rencontre une règle : automatique, soumise à une validation humaine, ou refusée. Le journal garde la décision, et il s’exporte.",
    platformFeatures: ["Règles d’action", "Validation humaine", "Journal exportable"],
    platformAction: "S’inscrire / Se connecter à la plateforme",
    platformLearn: "Ce que contient la plateforme",
    platformNote: "La console et les parcours d’intégration s’explorent en libre-service. La passerelle contraignante demande une installation, à préparer avec xSOM.",
    platformShotAlt: "La console AI Guard : registre des outils, règle effective pour l’outil choisi, et le récit d’un appel jusqu’à sa trace.",
    platformShotCaption: "La console d’inspection, avec des données de démonstration.",
    glossaryTitle: "Mettre des mots sur les risques.", glossaryBody: "Injection de prompt, fuite de données, empoisonnement… Des définitions claires et des exemples concrets.", glossaryAction: "Ouvrir le glossaire des menaces IA",
  },
  en: {
    navProducts: "Our products", navGlossary: "AI cyber threats",
    eyebrow: "Monitoring & cybersecurity · French expertise",
    title: ["Your AI use cases.", "Under your control."],
    intro: "French solutions to observe AI usage, control data sharing and govern AI actions throughout your organisation.",
    explore: "Explore use cases", productsLink: "Discover our products",
    principles: ["A sovereign approach", "Your data, your rules", "Everyday supervision"],
    videoPause: "Pause the background video", videoPlay: "Play the background video",
    usagesKicker: "01 / Understand the principle", usagesTitle: "Three worlds. One shared standard.",
    usagesIntro: "From workstations to models, AI is everywhere. Explore your organisation’s use cases and reveal the risks that come with them.",
    sceneTitle: "AI across your organisation", sceneNote: "Illustrative diagram",
    imageAlt: "An open architectural model: a development studio on the left, an employee workspace in the centre, and a models and data lab on the right.",
    toggle: "Show risks", choose: "Choose an AI environment",
    selectHint: "Select a space to explore it.", modeUsage: "Use cases", modeRisk: "Risks", everyday: "In your everyday work",
    controlsTitle: "The role of controls", controls: "Observe · Control · Trace", guardRole: "Controls close to your AI use cases",
    scope: "This diagram illustrates the principle. Available controls depend on the product, integrations and configured rules.",
    learnThreats: "Understand AI threats",
    universes: {
      development: {
        name: "Development", subtitle: "Code & automate", marker: "01", riskLabel: "Secrets & vulnerable code",
        daily: "An assistant to write code, explore a repository or run tasks. Each prompt and action can expose your system.",
        examples: ["Coding assistants", "Developer agents", "Tools & automation"],
        risks: ["Keys, tokens or passwords sent to AI.", "Vulnerable generated code or unverified dependencies.", "Agent actions beyond the permissions they need."],
        safeguards: ["Identify secrets before sending a prompt to the model.", "Govern agents’ tools and permissions.", "Trace decisions and require approval for sensitive actions."],
      },
      people: {
        name: "Employees", subtitle: "Write & decide", marker: "02", riskLabel: "Sensitive data exposed",
        daily: "Summarising a file, preparing a meeting or writing a document: AI supports everyday work, sometimes with confidential information.",
        examples: ["Everyday assistants", "Documents & summaries", "Internal search"],
        risks: ["Customer, HR or strategic data pasted into an assistant.", "AI services used outside the organisation’s framework.", "Fabricated answers mistaken for facts."],
        safeguards: ["Identify sensitive data in integrated traffic.", "Define authorised services and sharing rules.", "Keep human oversight over decisions."],
      },
      data: {
        name: "Models & data", subtitle: "Train & operate", marker: "03", riskLabel: "Compromised data & models",
        daily: "Training a model, grounding an assistant in your documents or using data: trust also depends on sources and access rights.",
        examples: ["Machine learning", "Knowledge bases & RAG", "Data pipelines"],
        risks: ["Poisoned training data or reference documents.", "Malicious instructions hidden in retrieved content.", "Information disclosed to an unauthorised person."],
        safeguards: ["Assess data provenance and access rights.", "Monitor exchanges with integrated models.", "Choose hosting, destinations and traceability."],
      },
    },
    productsKicker: "Our products", productsTitle: "Two products. Two moments of risk.",
    productsIntro: "The first guards the workstation, where the prompt leaves. The second guards the gateway, where the agent acts.",
    productsMeta: "Our products | xSOM AI Guard",
    productsDescription: "Secret Guard, the extension that holds secrets back before they reach the model, and the platform that governs what your AI agents do.",
    featured: "Individual / POC · Free", extensionTag: "The workstation",
    extensionTitle: "Secret Guard", extensionIntro: "The right check, before the prompt.",
    extensionBody: "The AI Guard extension spots keys, tokens and passwords in a supported assistant’s prompt, then pauses the send. The value stays on the machine: never displayed, never recorded, never transmitted.",
    extensionHosts: "VS Code and Copilot, Claude Code, Codex, Windsurf Cascade.",
    extensionFeatures: ["Local detection", "Explicit rules", "Checks before sending"],
    extensionAction: "Discover the free extension", extensionNote: "Local installation and explicit trust review in Codex. Plan managed enterprise deployment with xSOM.",
    extensionShotAlt: "The Secret Guard panel in VS Code: protection state, warning mode, configured assistants and enterprise gateway.",
    extensionShotCaption: "The panel, as it opens from the VS Code status bar.",
    platformTag: "The gateway", platformTitle: "AI Guard, the platform",
    platformIntro: "What the agent does, not only what it says.",
    platformBody: "The gateway sits between the agent and its tools. Every action meets a rule: automatic, held for human approval, or refused. The log keeps the decision, and it exports.",
    platformFeatures: ["Action rules", "Human approval", "Exportable log"],
    platformAction: "Sign up / Sign in to the platform",
    platformLearn: "What the platform includes",
    platformNote: "The console and the integration paths are self-serve. The binding gateway takes an install, to plan with xSOM.",
    platformShotAlt: "The AI Guard console: the tool registry, the effective rule for the selected tool, and one call told through to its trace.",
    platformShotCaption: "The inspection console, with demonstration data.",
    glossaryTitle: "Put a name to the risks.", glossaryBody: "Prompt injection, data leaks, poisoning… Clear definitions with concrete examples.", glossaryAction: "Open the AI threat glossary",
  },
} as const;

export type GuardHomeCopy = (typeof GUARD_HOME_COPY)[keyof typeof GUARD_HOME_COPY];
export type GuardUniverse = keyof GuardHomeCopy["universes"];
export const GUARD_UNIVERSES: GuardUniverse[] = ["development", "people", "data"];
