/** Public, illustrative positioning. Product availability stays on the offer pages. */
export const GUARD_HOME_COPY = {
  fr: {
    navProducts: "Nos Produits", navDevelopers: "Secret Guard", navGlossary: "Vos besoins", navCabinet: "Nos conseils",
    videoPause: "Mettre le fond vidéo en pause", videoPlay: "Lire le fond vidéo",
    usagesKicker: "01 / Comprendre le principe",
    usagesTitle: "Chaque usage de l’IA expose à des risques cyber différents.",
    imageAlt: "Bâtiment ouvert en trois espaces : équipe métier à gauche, développeurs au centre, équipe travaillant sur les modèles et les données d’entraînement à droite.",
    choose: "Choisir une équipe",
    exploreTeamRisks: "Explorer les risques liés à mon équipe",
    everyday: "Ce qui expose votre équipe",
    controlsTitle: "Le rôle des contrôles",
    universes: {
      development: {
        name: "Équipes de développement", subtitle: "Coder & automatiser", marker: "02",
        daily: "Les assistants et agents de code lisent vos dépôts, reçoivent des prompts et exécutent des outils. Secrets divulgués, code vulnérable et actions non autorisées deviennent des risques directs.",
        risks: ["Clés, jetons ou mots de passe envoyés à l’IA.", "Code généré vulnérable ou dépendances non vérifiées.", "Actions d’un agent au-delà des droits nécessaires."],
        safeguards: ["Repérer les secrets avant l’envoi au modèle.", "Encadrer les outils et les permissions des agents.", "Tracer les décisions et faire valider les actions sensibles."],
      },
      people: {
        name: "Équipes métier", subtitle: "Rédiger & décider", marker: "01",
        daily: "Les équipes métier confient documents et données à des assistants IA. Une information envoyée au mauvais service, une consigne cachée ou une réponse trompeuse peut peser sur leurs décisions.",
        risks: ["Données clients, RH ou stratégiques copiées dans un assistant.", "Services IA utilisés en dehors du cadre de l’entreprise.", "Réponses inventées prises pour des faits."],
        safeguards: ["Identifier les données sensibles dans les flux intégrés.", "Définir les services autorisés et les règles de partage.", "Garder une supervision humaine sur les décisions."],
      },
      data: {
        name: "Équipes modèles & données", subtitle: "Concevoir & entraîner", marker: "03",
        daily: "Conception, entraînement et déploiement exposent jeux de données, poids et pipelines. Empoisonnement, modèle compromis ou vol de poids peuvent altérer le système dès sa conception.",
        risks: ["Jeux de données d’entraînement empoisonnés.", "Modèles ou composants compromis dans la chaîne de développement.", "Poids du modèle volés ou comportement extrait par requêtes."],
        safeguards: ["Vérifier la provenance des données et des modèles.", "Contrôler les formats, composants et pipelines d’entraînement.", "Limiter les accès aux poids et aux services du modèle."],
      },
    },
    productsKicker: "Nos produits", productsTitle: "Du poste de travail à l’entreprise.",
    productsIntro: "Secret Guard protège le prompt local ; ses éditions Équipe et Renforcé étendent cette base aux règles, validations et preuves de l’agent. AI Guard garde la passerelle, là où l’agent agit.",
    productsMeta: "Nos produits",
    productsDescription: "Secret Guard, l’extension qui retient les secrets avant l’envoi au modèle, et la plateforme qui encadre les actions de vos agents IA.",
    featured: "Secret Guard Local · Gratuit", extensionTag: "Le poste de travail",
    extensionTitle: "Secret Guard", extensionIntro: "Le bon réflexe, avant le prompt.",
    extensionBody: "L’extension AI Guard repère les clés, les jetons et les mots de passe dans le prompt d’un assistant pris en charge, puis suspend l’envoi. La valeur reste sur le poste : elle n’est ni affichée, ni consignée, ni transmise.",
    extensionHosts: "GitHub Copilot, Claude Code et Codex.",
    extensionFeatures: ["Détection locale", "Règles explicites", "Contrôle avant l’envoi"],
    extensionAction: "Découvrir l’extension gratuite", extensionNote: "Installation locale et approbation explicite dans Codex. Parcours Entreprise administré à préparer avec xSOM.",
    extensionShotAlt: "Le panneau Secret Guard dans VS Code : état de la protection, mode d’avertissement, assistants configurés et passerelle d’entreprise.",
    extensionShotCaption: "Le panneau, tel qu’il s’ouvre depuis la barre d’état de VS Code.",
    platformTag: "La passerelle", platformTitle: "AI Guard, la plateforme",
    platformIntro: "Ce que l’agent fait, pas seulement ce qu’il dit.",
    platformBody: "La passerelle se place entre l’agent et ses outils. Chaque action rencontre une règle : automatique, soumise à une validation humaine, ou refusée. Le journal garde la décision, et il s’exporte.",
    platformFeatures: ["Règles d’action", "Validation humaine", "Journal exportable"],
    platformAction: "S’inscrire / Se connecter à la plateforme",
    platformLearn: "Ce que contient la plateforme",
    platformNote: "La console et les parcours d’intégration s’explorent en libre-service. La passerelle contraignante demande une installation, à préparer avec xSOM.",
    platformShotAlt: "La console AI Guard : registre des outils, règle effective pour l’outil choisi, et le récit d’un appel jusqu’à sa trace.",
    platformShotCaption: "La console d’inspection, avec des données de démonstration.",
    glossaryTitle: "Mettre des mots sur les risques.", glossaryBody: "Injection de prompt, fuite de secrets, empoisonnement… Chaque menace avec son attaque type, sa parade, les outils libres et ce que couvre AI Guard.", glossaryAction: "Ouvrir le glossaire des menaces IA",
  },
  en: {
    navProducts: "Our products", navDevelopers: "Secret Guard", navGlossary: "Your needs", navCabinet: "Our consulting",
    videoPause: "Pause the background video", videoPlay: "Play the background video",
    usagesKicker: "01 / Understand the principle", usagesTitle: "Every AI use case brings its own cyber risks.",
    imageAlt: "An open building with business teams on the left, software developers in the centre, and a team working on models and training data on the right.",
    choose: "Choose a team",
    everyday: "What exposes your team",
    exploreTeamRisks: "Explore risks for my team",
    controlsTitle: "The role of controls",
    universes: {
      development: {
        name: "Development teams", subtitle: "Code & automate", marker: "02",
        daily: "Coding assistants and agents read repositories, receive prompts and run tools. Exposed secrets, vulnerable code and unauthorised actions become direct risks for development teams.",
        risks: ["Keys, tokens or passwords sent to AI.", "Vulnerable generated code or unverified dependencies.", "Agent actions beyond the permissions they need."],
        safeguards: ["Identify secrets before sending a prompt to the model.", "Govern agents’ tools and permissions.", "Trace decisions and require approval for sensitive actions."],
      },
      people: {
        name: "Business teams", subtitle: "Write & decide", marker: "01",
        daily: "Business teams share documents and data with AI assistants. Information sent to the wrong service, hidden instructions or misleading answers can affect their decisions.",
        risks: ["Customer, HR or strategic data pasted into an assistant.", "AI services used outside the organisation’s framework.", "Fabricated answers mistaken for facts."],
        safeguards: ["Identify sensitive data in integrated traffic.", "Define authorised services and sharing rules.", "Keep human oversight over decisions."],
      },
      data: {
        name: "Model & data teams", subtitle: "Design & train", marker: "03",
        daily: "Design, training and deployment expose datasets, weights and pipelines. Poisoning, compromised models or stolen weights can affect the system from the outset.",
        risks: ["Poisoned training datasets.", "Compromised models or components in the development chain.", "Stolen model weights or behaviour extracted through queries."],
        safeguards: ["Verify the provenance of data and models.", "Check formats, components and training pipelines.", "Restrict access to weights and model services."],
      },
    },
    productsKicker: "Our products", productsTitle: "From workstation to organisation.",
    productsIntro: "Secret Guard protects the local prompt; its Team and Reinforced editions extend that base to agent rules, approvals and evidence. AI Guard protects the gateway where the agent acts.",
    productsMeta: "Our products",
    productsDescription: "Secret Guard, the extension that holds secrets back before they reach the model, and the platform that governs what your AI agents do.",
    featured: "Secret Guard Local · Free", extensionTag: "The workstation",
    extensionTitle: "Secret Guard", extensionIntro: "The right check, before the prompt.",
    extensionBody: "The AI Guard extension spots keys, tokens and passwords in a supported assistant’s prompt, then pauses the send. The value stays on the machine: never displayed, never recorded, never transmitted.",
    extensionHosts: "GitHub Copilot, Claude Code and Codex.",
    extensionFeatures: ["Local detection", "Explicit rules", "Checks before sending"],
    extensionAction: "Discover the free extension", extensionNote: "Local installation and explicit trust review in Codex. Plan managed enterprise deployment with xSOM.",
    extensionShotAlt: "The Secret Guard panel in VS Code: protection state, warning mode, configured assistants and enterprise gateway.",
    extensionShotCaption: "The panel, as it opens from the VS Code status bar.",
    platformTag: "The gateway", platformTitle: "AI Guard, the platform",
    platformIntro: "What the agent does, not only what it says.",
    platformBody: "The gateway sits between the agent and its tools. Every action meets a rule: automatic, held for human approval, or refused. The log keeps the decision, and it exports.",
    platformFeatures: ["Action rules", "Human approval", "Exportable log"],
    platformAction: "Sign up / Sign in to the platform",
    platformLearn: "What the platform includes",
    platformNote: "The console and the integration paths are self-serve. The binding gateway takes an install, to plan with xSOM.",
    platformShotAlt: "The AI Guard console: the tool registry, the effective rule for the selected tool, and one call told through to its trace.",
    platformShotCaption: "The inspection console, with demonstration data.",
    glossaryTitle: "Put a name to the risks.", glossaryBody: "Prompt injection, secret leakage, poisoning… Each threat with its typical attack, its mitigation, open-source tools and what AI Guard covers.", glossaryAction: "Open the AI threat glossary",
  },
} as const;

export type GuardHomeCopy = (typeof GUARD_HOME_COPY)[keyof typeof GUARD_HOME_COPY];
export type GuardUniverse = keyof GuardHomeCopy["universes"];
export const GUARD_UNIVERSES: GuardUniverse[] = ["people", "development", "data"];
