/** Public, illustrative positioning. Product availability stays on the offer pages. */
export const GUARD_HOME_COPY = {
  fr: {
    navUsages: "Nos usages", navProducts: "Nos produits", navGlossary: "Glossaire",
    eyebrow: "Monitoring & cybersécurité · Expertise française",
    title: ["Vos usages IA.", "Sous votre contrôle."],
    intro: "Des solutions françaises pour observer les usages, maîtriser les données et encadrer les actions de l’IA dans votre entreprise.",
    explore: "Explorer les usages", productsLink: "Découvrir nos produits",
    principles: ["Une approche souveraine", "Vos données, vos règles", "Une supervision au quotidien"],
    videoPause: "Mettre le fond vidéo en pause", videoPlay: "Lire le fond vidéo",
    usagesKicker: "01 / Comprendre le principe",
    usagesTitle: "Trois univers. Une même exigence.",
    usagesIntro: "Du poste de travail aux modèles, l’IA entre partout. Explorez les usages de votre entreprise et révélez les risques qui les accompagnent.",
    sceneTitle: "L’IA, à l’échelle de votre entreprise",
    sceneNote: "Schéma illustratif",
    imageAlt: "Maquette ouverte d’un bâtiment : un atelier de développement à gauche, un espace de travail collaboratif au centre, un laboratoire de modèles et de données à droite.",
    toggle: "Afficher les risques", choose: "Choisir un univers IA",
    selectHint: "Sélectionnez un espace pour l’explorer.",
    modeUsage: "Les usages", modeRisk: "Les risques", everyday: "Dans votre quotidien",
    controlsTitle: "Le rôle des contrôles", controls: "Observer · Contrôler · Tracer",
    guardRole: "Des contrôles au plus près de vos usages",
    scope: "Le schéma présente le principe. Les contrôles disponibles dépendent du produit, des intégrations et des règles configurées.",
    learnThreats: "Comprendre les menaces IA",
    universes: {
      development: {
        name: "Développement", subtitle: "Coder & automatiser", marker: "01", riskLabel: "Secrets & code vulnérable",
        daily: "Un assistant pour écrire du code, explorer un dépôt ou exécuter des tâches. Chaque prompt et chaque action peuvent exposer votre système.",
        examples: ["Assistants de code", "Agents développeurs", "Outils & automatisations"],
        risks: ["Clés, jetons ou mots de passe envoyés à l’IA.", "Code généré vulnérable ou dépendances non vérifiées.", "Actions d’un agent au-delà des droits nécessaires."],
        safeguards: ["Repérer les secrets avant l’envoi au modèle.", "Encadrer les outils et les permissions des agents.", "Tracer les décisions et faire valider les actions sensibles."],
      },
      people: {
        name: "Collaborateurs", subtitle: "Rédiger & décider", marker: "02", riskLabel: "Données sensibles exposées",
        daily: "Résumer un dossier, préparer une réunion, rédiger un document : l’IA facilite le travail quotidien, au contact d’informations parfois confidentielles.",
        examples: ["Assistants du quotidien", "Documents & synthèses", "Recherche interne"],
        risks: ["Données clients, RH ou stratégiques copiées dans un assistant.", "Services IA utilisés en dehors du cadre de l’entreprise.", "Réponses inventées prises pour des faits."],
        safeguards: ["Identifier les données sensibles dans les flux intégrés.", "Définir les services autorisés et les règles de partage.", "Garder une supervision humaine sur les décisions."],
      },
      data: {
        name: "Modèles & données", subtitle: "Entraîner & exploiter", marker: "03", riskLabel: "Corpus & modèles compromis",
        daily: "Entraîner un modèle, enrichir un assistant avec vos documents ou exploiter des données : la confiance dépend aussi des sources et des accès.",
        examples: ["Machine learning", "Bases documentaires & RAG", "Pipelines de données"],
        risks: ["Données d’entraînement ou documents de référence empoisonnés.", "Instructions malveillantes cachées dans les contenus consultés.", "Restitution d’informations à une personne non autorisée."],
        safeguards: ["Qualifier la provenance des données et les accès.", "Surveiller les échanges avec les modèles intégrés.", "Choisir l’hébergement, les destinations et la traçabilité."],
      },
    },
    productsKicker: "02 / Passer à l’action", productsTitle: "Découvrez nos produits.",
    productsIntro: "Un premier geste sur le poste de travail. Une supervision qui s’étend aux usages intégrés.",
    featured: "À la une · Extension en développement", extensionTitle: "AI Guard pour VS Code",
    extensionIntro: "Le bon réflexe, avant le prompt.",
    extensionBody: "Secret Guard, l’extension AI Guard, détecte localement les secrets dans les prompts des assistants pris en charge, avant leur envoi au modèle.",
    extensionFeatures: ["Détection locale", "Règles explicites", "Contrôle avant l’envoi"],
    extensionAction: "Découvrir l’extension", extensionNote: "Prototype disponible en VSIX. Compatibilités et périmètre sur la page produit.",
    preview: "Exemple illustratif", previewPrompt: "Peux-tu corriger ce script ?", previewSecret: "Clé d’API détectée", previewValue: "[valeur masquée]",
    previewDecision: "L’envoi est suspendu", previewDetail: "Retirez le secret avant de poursuivre.", previewLocal: "Analyse locale · aucune valeur affichée",
    platformTag: "Plateforme · POC", platformTitle: "La supervision de vos agents IA",
    platformBody: "Règles d’action, validations humaines et journal des décisions : explorez la console et les parcours d’intégration en libre-service.",
    platformAction: "Explorer la plateforme",
    glossaryTitle: "Mettre des mots sur les risques.", glossaryBody: "Injection de prompt, fuite de données, empoisonnement… Des définitions claires et des exemples concrets.", glossaryAction: "Ouvrir le glossaire des menaces IA",
  },
  en: {
    navUsages: "Use cases", navProducts: "Products", navGlossary: "Glossary",
    eyebrow: "Monitoring & cybersecurity · French expertise",
    title: ["Your AI use cases.", "Under your control."],
    intro: "French solutions to observe AI usage, control data sharing and govern AI actions throughout your organisation.",
    explore: "Explore use cases", productsLink: "Discover our products",
    principles: ["A sovereign approach", "Your data, your rules", "Everyday supervision"],
    videoPause: "Pause the background video", videoPlay: "Play the background video",
    usagesKicker: "01 / Understand the principle", usagesTitle: "Three worlds. One shared standard.",
    usagesIntro: "From workstations to models, AI is everywhere. Explore your organisation’s use cases and reveal the risks that come with them.",
    sceneTitle: "AI across your organisation", sceneNote: "Illustrative diagram",
    imageAlt: "An open architectural model: a development studio on the left, an employee workspace in the centre, and a models and data lab on the right.",
    toggle: "Show risks", choose: "Choose an AI environment",
    selectHint: "Select a space to explore it.", modeUsage: "Use cases", modeRisk: "Risks", everyday: "In your everyday work",
    controlsTitle: "The role of controls", controls: "Observe · Control · Trace", guardRole: "Controls close to your AI use cases",
    scope: "This diagram illustrates the principle. Available controls depend on the product, integrations and configured rules.",
    learnThreats: "Understand AI threats",
    universes: {
      development: {
        name: "Development", subtitle: "Code & automate", marker: "01", riskLabel: "Secrets & vulnerable code",
        daily: "An assistant to write code, explore a repository or run tasks. Each prompt and action can expose your system.",
        examples: ["Coding assistants", "Developer agents", "Tools & automation"],
        risks: ["Keys, tokens or passwords sent to AI.", "Vulnerable generated code or unverified dependencies.", "Agent actions beyond the permissions they need."],
        safeguards: ["Identify secrets before sending a prompt to the model.", "Govern agents’ tools and permissions.", "Trace decisions and require approval for sensitive actions."],
      },
      people: {
        name: "Employees", subtitle: "Write & decide", marker: "02", riskLabel: "Sensitive data exposed",
        daily: "Summarising a file, preparing a meeting or writing a document: AI supports everyday work, sometimes with confidential information.",
        examples: ["Everyday assistants", "Documents & summaries", "Internal search"],
        risks: ["Customer, HR or strategic data pasted into an assistant.", "AI services used outside the organisation’s framework.", "Fabricated answers mistaken for facts."],
        safeguards: ["Identify sensitive data in integrated traffic.", "Define authorised services and sharing rules.", "Keep human oversight over decisions."],
      },
      data: {
        name: "Models & data", subtitle: "Train & operate", marker: "03", riskLabel: "Compromised data & models",
        daily: "Training a model, grounding an assistant in your documents or using data: trust also depends on sources and access rights.",
        examples: ["Machine learning", "Knowledge bases & RAG", "Data pipelines"],
        risks: ["Poisoned training data or reference documents.", "Malicious instructions hidden in retrieved content.", "Information disclosed to an unauthorised person."],
        safeguards: ["Assess data provenance and access rights.", "Monitor exchanges with integrated models.", "Choose hosting, destinations and traceability."],
      },
    },
    productsKicker: "02 / Take action", productsTitle: "Discover our products.",
    productsIntro: "Start at the workstation. Extend supervision to your integrated use cases.",
    featured: "Featured · Extension in development", extensionTitle: "AI Guard for VS Code", extensionIntro: "The right check, before the prompt.",
    extensionBody: "Secret Guard, the AI Guard extension, detects secrets locally in prompts from supported assistants before they reach the model.",
    extensionFeatures: ["Local detection", "Explicit rules", "Checks before sending"],
    extensionAction: "Discover the extension", extensionNote: "Prototype available as a VSIX. See the product page for compatibility and scope.",
    preview: "Illustrative example", previewPrompt: "Can you fix this script?", previewSecret: "API key detected", previewValue: "[value redacted]",
    previewDecision: "Sending is paused", previewDetail: "Remove the secret before continuing.", previewLocal: "Local analysis · no value displayed",
    platformTag: "Platform · POC", platformTitle: "Supervise your AI agents",
    platformBody: "Action rules, human approvals and a decision log: explore the console and self-service integration paths.", platformAction: "Explore the platform",
    glossaryTitle: "Put a name to the risks.", glossaryBody: "Prompt injection, data leaks, poisoning… Clear definitions with concrete examples.", glossaryAction: "Open the AI threat glossary",
  },
} as const;

export type GuardHomeCopy = (typeof GUARD_HOME_COPY)[keyof typeof GUARD_HOME_COPY];
export type GuardUniverse = keyof GuardHomeCopy["universes"];
export const GUARD_UNIVERSES: GuardUniverse[] = ["development", "people", "data"];
