import type { Lang } from "@/lib/strings";

/**
 * Le glossaire opérationnel des menaces cyber de l'IA (`/menaces`).
 *
 * Chaque ligne croise cinq axes indépendants, et c'est ce qui la rend filtrable :
 * **l'usage** (qui est exposé), **la surface d'attaque** (par où l'attaque entre),
 * **l'impact** (ce qu'elle produit), **l'état de l'art** (ce que le marché sait en
 * faire) et **la couverture AI Guard** (ce que le POC livré en fait).
 *
 * **La couverture se lit sur la doctrine de `docs/product/THREAT-COVERAGE.md`**, pas
 * sur l'envie de cocher :
 *
 * - `yes` : un contrôle livré bloque ou retient l'action sur le chemin supervisé ;
 * - `partial` : il détecte, orchestre un outil tiers, atteste une mesure, ou ne tient
 *   qu'une facette de la menace ;
 * - `no` : aucun contrôle, et la note dit à qui revient la menace.
 *
 * Une ligne qui porte un `releve` pointe la ligne de la carte de couverture générée
 * (`lib/generated/threat-rows.json`). `e2e/glossary.spec.ts` interdit qu'elle revendique
 * plus que la carte : `yes` exige une facette `Bloqué`, `partial` une facette qui ne
 * soit pas hors périmètre. Revendiquer moins que la carte reste permis.
 *
 * Le classement éditorial des menaces, lui, reste à `lib/menaces.ts` et à `/evidence`.
 * Les exemples sont illustratifs ; les outils cités sont libres ou open source.
 */

export const GLOSSARY_USES = ["development", "workplace", "agents", "models"] as const;
export type GlossaryUse = (typeof GLOSSARY_USES)[number];

export const GLOSSARY_CATEGORIES = [
  "prompt",
  "agents",
  "rag",
  "model",
  "adversarial",
  "output",
  "privacy",
  "supply",
  "infra",
  "availability",
  "integrity",
  "human",
  "governance",
] as const;
export type GlossaryCategory = (typeof GLOSSARY_CATEGORIES)[number];

/** Par où l'attaque entre : ce qui est tapé, lu, appris, exécuté, cru ou hébergé. */
export const GLOSSARY_SURFACES = ["prompt", "data", "model", "actions", "people", "infra"] as const;
export type GlossarySurface = (typeof GLOSSARY_SURFACES)[number];

export const GLOSSARY_IMPACTS = [
  "leak",
  "manipulation",
  "action",
  "compromise",
  "cost",
  "fraud",
  "oversight",
] as const;
export type GlossaryImpact = (typeof GLOSSARY_IMPACTS)[number];

/** Du plus ouvert au mieux maîtrisé : cet ordre est aussi celui du tri « non résolu d'abord ». */
export const GLOSSARY_STATUSES = ["unsolved", "mitigated", "mixed", "solved"] as const;
export type GlossaryStatus = (typeof GLOSSARY_STATUSES)[number];

export const GLOSSARY_COVERAGES = ["yes", "partial", "no"] as const;
export type GlossaryCoverage = (typeof GLOSSARY_COVERAGES)[number];

type Localised = Record<Lang, string>;

/** Un nom d'outil est un nom propre, imprimé tel quel ; un contrôle générique se traduit. */
export type GlossaryTool = string | Localised;

export const OWASP = {
  LLM01: { title: "Prompt Injection", href: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/" },
  LLM02: { title: "Sensitive Information Disclosure", href: "https://genai.owasp.org/llmrisk/llm022025-sensitive-information-disclosure/" },
  LLM03: { title: "Supply Chain", href: "https://genai.owasp.org/llmrisk/llm032025-supply-chain/" },
  LLM04: { title: "Data and Model Poisoning", href: "https://genai.owasp.org/llmrisk/llm042025-data-and-model-poisoning/" },
  LLM05: { title: "Improper Output Handling", href: "https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/" },
  LLM06: { title: "Excessive Agency", href: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/" },
  LLM07: { title: "System Prompt Leakage", href: "https://genai.owasp.org/llmrisk/llm072025-system-prompt-leakage/" },
  LLM08: { title: "Vector and Embedding Weaknesses", href: "https://genai.owasp.org/llmrisk/llm082025-vector-and-embedding-weaknesses/" },
  LLM09: { title: "Misinformation", href: "https://genai.owasp.org/llmrisk/llm092025-misinformation/" },
  LLM10: { title: "Unbounded Consumption", href: "https://genai.owasp.org/llmrisk/llm102025-unbounded-consumption/" },
} as const;
export type OwaspCode = keyof typeof OWASP;

type GlossaryText = {
  title: string;
  /** L'attaque type et sa conséquence. */
  attack: string;
  /** La parade de référence du marché. */
  mitigation: string;
  /** Ce que fait le POC AI Guard, ou à qui revient la menace. */
  guard: string;
  /** La nuance de l'état de l'art, quand le statut seul ne la dit pas. */
  statusNote?: string;
};

/** Définition, exemple et premier réflexe : les fiches historiques du glossaire. */
type GlossaryExplainer = {
  definition: string;
  example: string;
  reflex: string;
};

export type GlossaryEntry = {
  id: string;
  category: GlossaryCategory;
  uses: readonly GlossaryUse[];
  surface: GlossarySurface;
  impact: GlossaryImpact;
  status: GlossaryStatus;
  coverage: GlossaryCoverage;
  tools: readonly GlossaryTool[];
  owasp?: OwaspCode;
  /** La ligne de `lib/generated/threat-rows.json` qui prouve la couverture. */
  releve?: string;
  copy: Record<Lang, GlossaryText>;
  explainer?: Record<Lang, GlossaryExplainer>;
};

const CONTAINERS: Localised = { fr: "Conteneurs", en: "Containers" };
const NO_MODEL_SCANNER: Localised = {
  fr: "Aucun analyseur d’artefacts de modèle n’est piloté par AI Guard.",
  en: "AI Guard orchestrates no model-artefact scanner.",
};
const MODEL_ROBUSTNESS: Localised = {
  fr: "La robustesse du modèle revient à celui qui l’entraîne, pas à la passerelle qui l’appelle.",
  en: "Model robustness belongs to whoever trains the model, not to the gateway that calls it.",
};
const MODEL_OUT_OF_SCOPE: Localised = {
  fr: "AI Guard ne protège pas le modèle lui-même : ses poids et ses sorties restent hors périmètre.",
  en: "AI Guard does not protect the model itself: its weights and outputs are out of scope.",
};
const SAME_PROMPT_GUARD: Localised = {
  fr: "Le garde-prompt tiers classe aussi le jailbreak ; son verdict est chaîné, sans blocage. Le modèle contourné n’exécute pas pour autant d’action irréversible sans validation humaine.",
  en: "The third-party prompt guard also flags jailbreaks; its verdict is chained, without blocking. A jailbroken model still cannot run an irreversible action without human approval.",
};
const PROVENANCE: Localised = {
  fr: "Provenance des jeux de données déclarée, datée et périssable, publiée dans l’Evidence Pack : une attestation, pas un contrôle des données.",
  en: "Dataset provenance is declared, dated and expiring, then published in the Evidence Pack: an attestation, not a check of the data.",
};

export const THREAT_GLOSSARY: readonly GlossaryEntry[] = [
  // --- Prompts & instructions ------------------------------------------------
  {
    id: "injection-directe",
    category: "prompt",
    uses: ["development", "workplace", "agents"],
    surface: "prompt",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["NeMo Guardrails", "garak", "Promptfoo", "PyRIT", "Giskard"],
    owasp: "LLM01",
    releve: "M-01",
    copy: {
      fr: {
        title: "Injection de prompt directe",
        attack: "Un utilisateur demande au modèle d’ignorer les règles du développeur ou du système.",
        mitigation: "Frontières d’instructions strictes, filtrage des entrées, moindre privilège, validation des sorties, red teaming.",
        guard: "Aucun filtrage natif du prompt : un garde-prompt tiers est orchestré et son verdict chaîné, sans blocage. L’action irréversible qui en découlerait attend une validation humaine.",
        statusNote: "Atténué, pas résolu",
      },
      en: {
        title: "Direct prompt injection",
        attack: "A user instructs the model to ignore developer or system rules.",
        mitigation: "Strong instruction boundaries, input filtering, least privilege, output validation, red teaming.",
        guard: "No native prompt filtering: a third-party prompt guard is orchestrated and its verdict chained, without blocking. Any resulting irreversible action waits for human approval.",
        statusNote: "Mitigated, not solved",
      },
    },
  },
  {
    id: "injection-de-prompt",
    category: "prompt",
    uses: ["development", "workplace", "agents", "models"],
    surface: "data",
    impact: "action",
    status: "unsolved",
    coverage: "yes",
    tools: ["NeMo Guardrails", "Promptfoo", "garak"],
    owasp: "LLM01",
    releve: "M-02",
    copy: {
      fr: {
        title: "Injection de prompt indirecte",
        attack: "Une consigne malveillante est cachée dans une page web, un e-mail, un PDF, un enregistrement de base ou un document RAG.",
        mitigation: "Traiter les données récupérées comme non fiables ; séparer instructions et contenu ; permissions d’outils ; confirmation.",
        guard: "Garde de taint sur les résultats d’outils, en quatre langues, Unicode et base64 normalisés : après un contenu suspect, l’action irréversible ou l’envoi externe est suspendu ou refusé.",
        statusNote: "Problème difficile, non résolu",
      },
      en: {
        title: "Indirect prompt injection",
        attack: "A malicious instruction is hidden in a web page, email, PDF, database record or RAG document.",
        mitigation: "Treat retrieved data as untrusted; separate instructions from content; tool permissions; confirmation.",
        guard: "Taint guard on tool results, in four languages, with Unicode and base64 normalised: after suspicious content, irreversible actions and external sends are held or denied.",
        statusNote: "Hard unsolved problem",
      },
    },
    explainer: {
      fr: {
        definition: "Des instructions introduites dans un message, une page ou un document tentent de détourner l’IA de sa tâche.",
        example: "Un document à résumer contient une consigne demandant à l’assistant d’envoyer des informations internes ailleurs.",
        reflex: "Traiter les contenus externes comme non fiables et limiter les actions accessibles à l’agent.",
      },
      en: {
        definition: "Instructions placed in a message, webpage or document attempt to divert the AI from its intended task.",
        example: "A document being summarised tells the assistant to send internal information to another destination.",
        reflex: "Treat external content as untrusted and limit the actions available to the agent.",
      },
    },
  },
  {
    id: "injection-persistante",
    category: "prompt",
    uses: ["workplace", "agents", "models"],
    surface: "data",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["Promptfoo", { fr: "Filtres RAG sur mesure", en: "Custom RAG filters" }],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Injection de prompt persistante",
        attack: "Un texte malveillant stocké en mémoire ou dans une base vectorielle influence les sessions suivantes.",
        mitigation: "Provenance, assainissement à l’ingestion, zones de confiance, ACL sur la recherche.",
        guard: "Repérée par la garde de taint quand elle revient par un outil de la passerelle ; la mémoire et la base elles-mêmes ne sont pas assainies.",
      },
      en: {
        title: "Stored prompt injection",
        attack: "Malicious text stored in memory or a vector database affects future sessions.",
        mitigation: "Provenance, sanitised ingestion, trust zones, retrieval ACLs.",
        guard: "Caught by the taint guard when it comes back through a gateway tool; the memory or store itself is not cleaned.",
      },
    },
  },
  {
    id: "jailbreak",
    category: "prompt",
    uses: ["development", "workplace", "agents"],
    surface: "prompt",
    impact: "manipulation",
    status: "unsolved",
    coverage: "partial",
    tools: ["garak", "PyRIT", "Promptfoo", "DeepTeam"],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Jailbreak",
        attack: "Des prompts adverses contournent les protections du modèle.",
        mitigation: "Alignement de sécurité, classifieurs, garde-fous à l’exécution et tests continus.",
        guard: SAME_PROMPT_GUARD.fr,
        statusNote: "Pas de solution universelle",
      },
      en: {
        title: "Jailbreaking",
        attack: "Adversarial prompts get around the model’s safety controls.",
        mitigation: "Safety tuning, classifiers, runtime guardrails and continuous testing.",
        guard: SAME_PROMPT_GUARD.en,
        statusNote: "No universal solution",
      },
    },
  },
  {
    id: "extraction-prompt-systeme",
    category: "prompt",
    uses: ["development", "agents"],
    surface: "prompt",
    impact: "leak",
    status: "mitigated",
    coverage: "partial",
    tools: ["garak", "Promptfoo", "PyRIT"],
    owasp: "LLM07",
    releve: "M-14",
    copy: {
      fr: {
        title: "Extraction du prompt système",
        attack: "Le modèle est amené à révéler ses instructions cachées ou sa configuration.",
        mitigation: "Ne jamais placer de vrai secret dans un prompt ; isoler les secrets ; filtrer les sorties.",
        guard: "La régurgitation verbatim du prompt système est détectée dans les réponses ; une paraphrase échappe au détecteur. Les secrets restent au coffre, jamais dans le prompt.",
      },
      en: {
        title: "System-prompt extraction",
        attack: "The model is tricked into revealing its hidden instructions or configuration.",
        mitigation: "Never put real secrets in prompts; isolate secrets; filter outputs.",
        guard: "Verbatim regurgitation of the system prompt is detected in responses; a paraphrase slips past. Secrets stay in the vault, never in the prompt.",
      },
    },
  },
  {
    id: "detournement-de-contexte",
    category: "prompt",
    uses: ["workplace", "agents"],
    surface: "data",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["Guardrails", { fr: "Moteur de policy maison", en: "Custom policy engine" }],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Détournement de contexte",
        attack: "Un contenu moins fiable prend le pas sur les instructions de confiance.",
        mitigation: "Hiérarchie des instructions et segmentation du contexte.",
        guard: "Le contenu peu fiable issu des outils marque la session et retient les actions à risque qui suivent. Le contexte du modèle, lui, n’est pas segmenté.",
      },
      en: {
        title: "Context hijacking",
        attack: "Lower-trust content comes to dominate higher-trust instructions.",
        mitigation: "Instruction hierarchy and context segmentation.",
        guard: "Low-trust content from tools taints the session and holds the risky actions that follow. The model’s context itself is not segmented.",
      },
    },
  },
  {
    id: "obfuscation",
    category: "prompt",
    uses: ["development", "agents"],
    surface: "prompt",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["PyRIT", "Promptfoo", { fr: "Bibliothèques de sécurité Unicode", en: "Unicode security libraries" }],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Attaques par encodage et obfuscation",
        attack: "Base64, Unicode, homoglyphes, ROT ou caractères invisibles déjouent les filtres.",
        mitigation: "Canoniser et normaliser les entrées ; décoder avant d’analyser.",
        guard: "Les résultats d’outils sont normalisés (NFKC, homoglyphes, caractères invisibles) et le base64 décodé avant l’analyse ; le prompt de l’utilisateur ne l’est pas.",
      },
      en: {
        title: "Encoding and obfuscation attacks",
        attack: "Base64, Unicode, homoglyphs, ROT or invisible characters defeat filters.",
        mitigation: "Canonicalise and normalise input; decode before scanning.",
        guard: "Tool results are normalised (NFKC, homoglyphs, invisible characters) and base64 decoded before scanning; the user’s prompt is not.",
      },
    },
  },
  {
    id: "jailbreak-multilingue",
    category: "prompt",
    uses: ["workplace", "agents"],
    surface: "prompt",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["garak", "Promptfoo"],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Jailbreak multilingue",
        attack: "L’attaque est formulée dans une langue peu dotée pour échapper aux filtres de sécurité.",
        mitigation: "Classifieurs de sécurité multilingues et tests adverses.",
        guard: "Même garde-prompt tiers, chaîné sans blocage ; son efficacité dans les langues peu dotées n’est pas mesurée.",
      },
      en: {
        title: "Multilingual jailbreak",
        attack: "The attack is written in a low-resource language to slip past safety filters.",
        mitigation: "Multilingual safety classifiers and adversarial tests.",
        guard: "The same third-party prompt guard, chained without blocking; its accuracy in low-resource languages is not measured.",
      },
    },
  },
  {
    id: "injection-multimodale",
    category: "prompt",
    uses: ["workplace", "agents", "models"],
    surface: "data",
    impact: "manipulation",
    status: "unsolved",
    coverage: "no",
    tools: [{ fr: "Outils de recherche", en: "Research tooling" }, { fr: "Red teaming multimodal", en: "Multimodal red teaming" }],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Injection de prompt multimodale",
        attack: "Des instructions sont cachées dans une image, un son ou une vidéo.",
        mitigation: "Séparer perception et exécution ; OCR et inspection du contenu ; pas d’usage autonome des outils.",
        guard: "Images, sons et vidéos ne sont pas inspectés par AI Guard.",
        statusNote: "Émergent",
      },
      en: {
        title: "Multimodal prompt injection",
        attack: "Instructions are hidden in an image, audio or video.",
        mitigation: "Separate perception from execution; OCR and content inspection; no autonomous tool use.",
        guard: "AI Guard does not inspect images, audio or video.",
        statusNote: "Emerging",
      },
    },
  },

  // --- Agents ---------------------------------------------------------------
  {
    id: "autonomie-excessive",
    category: "agents",
    uses: ["development", "workplace", "agents"],
    surface: "actions",
    impact: "action",
    status: "solved",
    coverage: "yes",
    tools: ["Open Policy Agent (OPA)", CONTAINERS],
    owasp: "LLM06",
    releve: "M-12",
    copy: {
      fr: {
        title: "Autonomie excessive",
        attack: "L’agent dispose de plus de droits que sa tâche n’en exige.",
        mitigation: "Moindre privilège, portées par outil, approbation humaine, bac à sable.",
        guard: "RBAC par outil, jetons à portée limitée, outil inconnu refusé, validation humaine des actions irréversibles.",
        statusNote: "Parades solides",
      },
      en: {
        title: "Excessive agency",
        attack: "The agent holds more permissions than its task requires.",
        mitigation: "Least privilege, per-tool scopes, human approval, sandboxing.",
        guard: "Per-tool RBAC, scoped tokens, unknown tools denied, human approval for irreversible actions.",
        statusNote: "Strong mitigations",
      },
    },
    explainer: {
      fr: {
        definition: "Un agent dispose de trop de droits ou de liberté pour agir. Une erreur peut alors modifier, publier ou supprimer des informations.",
        example: "Un assistant chargé de préparer une réponse peut aussi l’envoyer, sans validation du collaborateur.",
        reflex: "Accorder uniquement les droits nécessaires et faire valider les actions à fort impact.",
      },
      en: {
        definition: "An agent has more permissions or freedom than it needs. A mistake can then change, publish or delete information.",
        example: "An assistant asked to draft a reply can also send it without the employee’s approval.",
        reflex: "Grant only necessary permissions and require approval for high-impact actions.",
      },
    },
  },
  {
    id: "injection-appel-outil",
    category: "agents",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "action",
    status: "mitigated",
    coverage: "yes",
    tools: ["OPA", "Guardrails"],
    owasp: "LLM06",
    releve: "M-06",
    copy: {
      fr: {
        title: "Injection d’appels d’outils",
        attack: "Un prompt pousse le modèle à appeler des fonctions dangereuses.",
        mitigation: "Schémas explicites, validation, contrôle de policy autour de chaque appel.",
        guard: "Chaque appel traverse la chaîne déterministe : intégrité, RBAC, policy et prédicats sur les arguments, risque, taint, puis validation humaine.",
      },
      en: {
        title: "Tool and function-call injection",
        attack: "A prompt steers the model into calling dangerous functions.",
        mitigation: "Explicit schemas, validation, policy checks around every call.",
        guard: "Every call goes through the deterministic chain: integrity, RBAC, policy and argument predicates, risk, taint, then human approval.",
      },
    },
  },
  {
    id: "depute-confus",
    category: "agents",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "action",
    status: "solved",
    coverage: "yes",
    tools: ["OPA", { fr: "Portées OAuth", en: "OAuth scopes" }],
    owasp: "LLM06",
    releve: "M-12",
    copy: {
      fr: {
        title: "Député confus",
        attack: "L’IA met son autorité légitime au service d’un attaquant.",
        mitigation: "Lier l’autorisation à l’utilisateur, pas au modèle ; jetons de capacité.",
        guard: "Garde du député confus : un outil réservé à certains clients refuse tout agent qui n’en relève pas, quelle que soit la classe de l’action.",
        statusNote: "Schéma de sécurité établi",
      },
      en: {
        title: "Confused deputy",
        attack: "The AI uses its legitimate authority on an attacker’s behalf.",
        mitigation: "Bind authorisation to the user, not the model; capability tokens.",
        guard: "Confused-deputy guard: a tool pinned to certain clients refuses any agent outside them, whatever the action class.",
        statusNote: "Established security pattern",
      },
    },
  },
  {
    id: "escalade-privileges-agent",
    category: "agents",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "action",
    status: "solved",
    coverage: "yes",
    tools: ["OPA", "SELinux", "AppArmor", CONTAINERS],
    owasp: "LLM06",
    releve: "M-12",
    copy: {
      fr: {
        title: "Élévation de privilèges d’un agent",
        attack: "L’agent atteint des API d’administration, des fichiers ou des ressources cloud.",
        mitigation: "RBAC ou ABAC, bac à sable, comptes de service distincts.",
        guard: "Seuls les outils approuvés et autorisés à l’agent sont exposés ; un outil inconnu est refusé par défaut.",
      },
      en: {
        title: "Agent privilege escalation",
        attack: "The agent reaches admin APIs, files or cloud resources.",
        mitigation: "RBAC or ABAC, sandboxing, separate service accounts.",
        guard: "Only approved tools the agent is allowed to use are exposed; an unknown tool is denied by default.",
      },
    },
  },
  {
    id: "transactions-non-autorisees",
    category: "agents",
    uses: ["workplace", "agents"],
    surface: "actions",
    impact: "action",
    status: "solved",
    coverage: "yes",
    tools: [{ fr: "Moteurs de workflow", en: "Workflow engines" }, "OPA"],
    owasp: "LLM06",
    releve: "M-06",
    copy: {
      fr: {
        title: "Transactions non autorisées",
        attack: "L’IA envoie un e-mail ou de l’argent, supprime des données ou modifie l’infrastructure.",
        mitigation: "Approbation humaine des opérations lourdes de conséquences ; plafonds de transaction.",
        guard: "Le cœur du produit : l’action irréversible est présentée en dry-run et n’a lieu qu’après approbation. Délai dépassé ou service indisponible, elle est refusée.",
      },
      en: {
        title: "Unauthorised transactions",
        attack: "The AI sends email or money, deletes data or changes infrastructure.",
        mitigation: "Human approval for consequential operations; transaction limits.",
        guard: "The product’s core: an irreversible action is shown as a dry-run and only runs once approved. On timeout or outage, it is denied.",
      },
    },
  },
  {
    id: "boucle-agent",
    category: "agents",
    uses: ["agents"],
    surface: "actions",
    impact: "cost",
    status: "solved",
    coverage: "partial",
    tools: [{ fr: "Contrôles applicatifs", en: "Application controls" }],
    owasp: "LLM10",
    copy: {
      fr: {
        title: "Boucle d’agent incontrôlée",
        attack: "Un agent récursif consomme des ressources ou répète ses actions sans fin.",
        mitigation: "Nombre maximal d’étapes, budgets d’exécution, délais, coupe-circuits.",
        guard: "L’ordre d’arrêt de l’opérateur est relu à chaque appel et le proxy LLM impose un quota par minute ; aucun plafond d’étapes par tâche.",
      },
      en: {
        title: "Agent loop and runaway automation",
        attack: "A recursive agent consumes resources or acts over and over.",
        mitigation: "Step limits, execution budgets, timeouts, circuit breakers.",
        guard: "The operator’s stop order is re-read on every call and the LLM proxy enforces a per-minute quota; there is no per-task step limit.",
      },
    },
  },
  {
    id: "injection-inter-agents",
    category: "agents",
    uses: ["agents"],
    surface: "data",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["OPA", { fr: "Validation sur mesure", en: "Custom validation" }],
    owasp: "LLM01",
    copy: {
      fr: {
        title: "Injection entre agents",
        attack: "Un agent compromis transmet des instructions malveillantes à un autre agent.",
        mitigation: "Authentifier les messages entre agents ; protocoles structurés ; séparation des niveaux de confiance.",
        guard: "Chaque agent s’authentifie par son propre jeton, et ce qu’un autre agent renvoie par un outil passe par la garde de taint. Les messages directs entre agents ne sont pas vus.",
      },
      en: {
        title: "Cross-agent injection",
        attack: "A compromised agent sends malicious instructions to another agent.",
        mitigation: "Authenticate agent messages; structured protocols; trust separation.",
        guard: "Each agent authenticates with its own token, and what another agent returns through a tool goes through the taint guard. Direct agent-to-agent messages are not seen.",
      },
    },
  },
  {
    id: "memoire-empoisonnee",
    category: "agents",
    uses: ["agents"],
    surface: "data",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: [{ fr: "ACL de base vectorielle", en: "Vector DB ACLs" }, { fr: "Contrôles sur mesure", en: "Custom controls" }],
    copy: {
      fr: {
        title: "Mémoire d’agent empoisonnée",
        attack: "Un attaquant implante de faux souvenirs ou des consignes malveillantes dans la mémoire longue de l’agent.",
        mitigation: "Provenance, autorisation d’écriture, expiration, journaux immuables.",
        guard: "Une écriture en mémoire faite par un outil passe par la policy et entre dans la chaîne d’audit ; le contenu mémorisé n’est pas vérifié.",
      },
      en: {
        title: "Agent memory poisoning",
        attack: "An attacker implants false or malicious long-term memories in the agent.",
        mitigation: "Provenance, write authorisation, expiry, immutable logs.",
        guard: "A memory write made through a tool goes through the policy and into the audit chain; the stored content is not checked.",
      },
    },
  },
  {
    id: "outil-piege",
    category: "agents",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "action",
    status: "mitigated",
    coverage: "yes",
    tools: ["mcp-scan", { fr: "Épinglage des outils", en: "Tool pinning" }],
    owasp: "LLM03",
    releve: "M-11",
    copy: {
      fr: {
        title: "Outil piégé (tool poisoning, rug pull)",
        attack: "Un serveur d’outils cache des consignes dans sa description, ou la modifie discrètement après validation.",
        mitigation: "Épingler et relire les définitions d’outils ; détecter leurs changements ; liste blanche de serveurs.",
        guard: "Chaque outil a son empreinte : un outil nouveau ou modifié reste en quarantaine jusqu’à approbation.",
      },
      en: {
        title: "Tool poisoning and rug pull",
        attack: "A tool server hides instructions in its description, or quietly changes it after approval.",
        mitigation: "Pin and review tool definitions; detect changes; allowlist servers.",
        guard: "Every tool is fingerprinted: a new or changed tool stays quarantined until approved.",
      },
    },
  },
  {
    id: "identite-empruntee",
    category: "agents",
    uses: ["workplace", "agents"],
    surface: "actions",
    impact: "oversight",
    status: "mitigated",
    coverage: "yes",
    tools: ["SPIFFE/SPIRE", { fr: "Comptes de service dédiés", en: "Dedicated service accounts" }],
    copy: {
      fr: {
        title: "Agent sous identité humaine",
        attack: "L’agent emprunte les accès d’une personne ; après coup, rien ne distingue ce qu’il a fait de ce qu’elle a fait.",
        mitigation: "Identités propres aux agents, accès de courte durée, journaux attribués.",
        guard: "Chaque agent présente son propre jeton ; chaque décision lui est attribuée dans la chaîne d’audit.",
      },
      en: {
        title: "Agent acting under a human identity",
        attack: "The agent uses a person’s credentials; afterwards nothing separates what it did from what the person did.",
        mitigation: "Dedicated agent identities, short-lived credentials, attributed logs.",
        guard: "Each agent presents its own token; every decision is attributed to it in the audit chain.",
      },
    },
  },
  {
    id: "delegation-en-cascade",
    category: "agents",
    uses: ["agents"],
    surface: "actions",
    impact: "action",
    status: "unsolved",
    coverage: "partial",
    tools: ["OPA", { fr: "Échange de jetons OAuth", en: "OAuth token exchange" }],
    copy: {
      fr: {
        title: "Délégation en cascade entre agents",
        attack: "Un agent en appelle un autre, qui en appelle un troisième ; plus personne ne vérifie au nom de qui agit le dernier.",
        mitigation: "Propager le mandat d’origine et le vérifier à chaque étape.",
        guard: "Chaque agent est authentifié et limité à ses propres outils à la passerelle ; la chaîne de délégation n’est pas reconstituée.",
        statusNote: "Émergent",
      },
      en: {
        title: "Cascading delegation between agents",
        attack: "One agent calls another, which calls a third; nobody checks any more on whose behalf the last one acts.",
        mitigation: "Propagate the original mandate and check it at every hop.",
        guard: "Each agent is authenticated and limited to its own tools at the gateway; the delegation chain is not reconstructed.",
        statusNote: "Emerging",
      },
    },
  },

  // --- RAG ------------------------------------------------------------------
  {
    id: "empoisonnement-rag",
    category: "rag",
    uses: ["workplace", "agents", "models"],
    surface: "data",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["Promptfoo", "Giskard"],
    owasp: "LLM08",
    releve: "M-03",
    copy: {
      fr: {
        title: "Empoisonnement du RAG",
        attack: "Un attaquant dépose des documents malveillants que l’IA ira ensuite chercher.",
        mitigation: "Sources de confiance en liste blanche, signature des documents, provenance, détection d’anomalies.",
        guard: "Provenance des corpus déclarée, datée et publiée dans l’Evidence Pack ; un document récupéré par un outil passe par la garde de taint.",
      },
      en: {
        title: "RAG poisoning",
        attack: "An attacker plants malicious documents that the AI later retrieves.",
        mitigation: "Trusted-source allowlists, document signing, provenance, anomaly detection.",
        guard: "Corpus provenance is declared, dated and published in the Evidence Pack; a document retrieved through a tool goes through the taint guard.",
      },
    },
  },
  {
    id: "empoisonnement-vectoriel",
    category: "rag",
    uses: ["agents", "models"],
    surface: "data",
    impact: "manipulation",
    status: "mixed",
    coverage: "partial",
    tools: ["Qdrant (ACL)", "Milvus (ACL)"],
    owasp: "LLM08",
    releve: "M-03",
    copy: {
      fr: {
        title: "Empoisonnement de la base vectorielle",
        attack: "Des embeddings ou des contenus altérés faussent la recherche.",
        mitigation: "Authentification, validation des documents, contrôles d’intégrité.",
        guard: "Même déclaration de provenance des corpus ; aucun contrôle d’intégrité sur les vecteurs eux-mêmes.",
      },
      en: {
        title: "Vector DB poisoning",
        attack: "Tampered embeddings or content skew retrieval.",
        mitigation: "Authentication, document validation, integrity controls.",
        guard: "The same corpus provenance declaration; no integrity check on the vectors themselves.",
      },
    },
  },
  {
    id: "inversion-embeddings",
    category: "rag",
    uses: ["models"],
    surface: "data",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: [{ fr: "Chiffrement et contrôle d’accès standard", en: "Standard crypto and access control" }],
    owasp: "LLM08",
    copy: {
      fr: {
        title: "Inversion d’embeddings",
        attack: "Des informations sensibles sont reconstituées à partir des embeddings.",
        mitigation: "Limiter les embeddings sensibles ; chiffrement et contrôle d’accès.",
        guard: "AI Guard ne s’interpose pas devant la base vectorielle.",
      },
      en: {
        title: "Embedding inversion",
        attack: "Sensitive information is reconstructed from embeddings.",
        mitigation: "Minimise sensitive embeddings; encryption and access control.",
        guard: "AI Guard does not sit in front of the vector store.",
      },
    },
  },
  {
    id: "acces-rag",
    category: "rag",
    uses: ["workplace", "models"],
    surface: "data",
    impact: "leak",
    status: "solved",
    coverage: "no",
    tools: ["OPA", { fr: "ACL de base vectorielle", en: "Vector-store ACLs" }],
    owasp: "LLM08",
    copy: {
      fr: {
        title: "Accès indu aux documents du RAG",
        attack: "Un utilisateur obtient des documents qu’il n’a pas le droit de consulter.",
        mitigation: "Autorisation avant la recherche ; ACL par document.",
        guard: "La médiation du RAG est hors du périmètre du POC : AI Guard ne rejoue pas les droits du demandeur au moment de la recherche.",
      },
      en: {
        title: "Retrieval data leakage",
        attack: "A user retrieves documents they are not allowed to see.",
        mitigation: "Authorisation before retrieval; per-document ACLs.",
        guard: "RAG mediation is outside the POC’s scope: AI Guard does not replay the requester’s rights at retrieval time.",
      },
    },
    explainer: {
      fr: {
        definition: "Un assistant enrichi par une base documentaire (RAG) récupère des contenus sans respecter les droits de la personne qui l’interroge.",
        example: "L’assistant interne cite un dossier RH à un collaborateur qui ne peut pas ouvrir ce dossier.",
        reflex: "Appliquer les droits d’accès lors de la recherche et cloisonner les bases documentaires.",
      },
      en: {
        definition: "An assistant using a knowledge base (RAG) retrieves documents without respecting the requesting user’s permissions.",
        example: "An internal assistant quotes an HR file to an employee who cannot open that file.",
        reflex: "Enforce access permissions during retrieval and separate document collections appropriately.",
      },
    },
  },
  {
    id: "fuite-inter-clients-rag",
    category: "rag",
    uses: ["workplace", "models"],
    surface: "data",
    impact: "leak",
    status: "solved",
    coverage: "no",
    tools: [{ fr: "ACL de base de données et vectorielle", en: "Database and vector DB ACLs" }],
    owasp: "LLM08",
    copy: {
      fr: {
        title: "Fuite entre clients dans le RAG",
        attack: "Le client A récupère les données du client B.",
        mitigation: "Cloisonnement strict des espaces de noms et authentification liée au client.",
        guard: "AI Guard cloisonne ses propres données par RLS Postgres, mais ne s’interpose pas devant votre base RAG.",
      },
      en: {
        title: "Cross-tenant RAG leakage",
        attack: "Tenant A retrieves tenant B’s data.",
        mitigation: "Strong namespace isolation and tenant-bound authentication.",
        guard: "AI Guard isolates its own data with Postgres RLS, but does not sit in front of your RAG store.",
      },
    },
  },

  // --- Modèle & entraînement -------------------------------------------------
  {
    id: "empoisonnement",
    category: "model",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: [{ fr: "Frameworks de validation de données", en: "Data validation frameworks" }, "ART"],
    owasp: "LLM04",
    releve: "M-03",
    copy: {
      fr: {
        title: "Empoisonnement des données d’entraînement",
        attack: "Un attaquant injecte des échantillons manipulés dans les données d’entraînement.",
        mitigation: "Provenance des jeux de données, assainissement, détection d’anomalies, écriture restreinte.",
        guard: PROVENANCE.fr,
      },
      en: {
        title: "Training-data poisoning",
        attack: "An attacker injects manipulated samples into the training data.",
        mitigation: "Dataset provenance, sanitisation, anomaly detection, restricted write access.",
        guard: PROVENANCE.en,
      },
    },
    explainer: {
      fr: {
        definition: "Des données d’apprentissage ou un modèle sont altérés pour influencer les résultats ou introduire un comportement caché.",
        example: "Un jeu de données modifié apprend au modèle à favoriser systématiquement une réponse choisie par l’attaquant.",
        reflex: "Tracer la provenance des données, contrôler leurs modifications et évaluer le modèle avant déploiement.",
      },
      en: {
        definition: "Training data or a model is tampered with to influence results or introduce hidden behaviour.",
        example: "A modified dataset teaches the model to consistently favour an answer selected by an attacker.",
        reflex: "Track data provenance, review changes and evaluate the model before deployment.",
      },
    },
  },
  {
    id: "empoisonnement-fine-tuning",
    category: "model",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["garak", "Giskard", "ART"],
    owasp: "LLM04",
    releve: "M-03",
    copy: {
      fr: {
        title: "Empoisonnement du fine-tuning",
        attack: "Des exemples malveillants modifient délibérément le comportement du modèle.",
        mitigation: "Jeux de données de confiance, tests différentiels, évaluation du modèle.",
        guard: "Même déclaration de provenance des jeux de données ; le modèle affiné n’est pas évalué par AI Guard.",
      },
      en: {
        title: "Fine-tuning poisoning",
        attack: "Malicious examples deliberately shift the model’s behaviour.",
        mitigation: "Trusted datasets, differential testing, model evaluation.",
        guard: "The same dataset provenance declaration; AI Guard does not evaluate the fine-tuned model.",
      },
    },
  },
  {
    id: "modele-piege",
    category: "model",
    uses: ["development", "models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "no",
    tools: ["ModelScan", "Fickling", "garak"],
    owasp: "LLM04",
    copy: {
      fr: { title: "Modèle piégé (backdoor)", attack: "Un déclencheur caché active un comportement malveillant.", mitigation: "Provenance du modèle, analyse, tests comportementaux.", guard: NO_MODEL_SCANNER.fr },
      en: { title: "Backdoored model", attack: "A hidden trigger switches on malicious behaviour.", mitigation: "Model provenance, scanning, behavioural testing.", guard: NO_MODEL_SCANNER.en },
    },
  },
  {
    id: "alteration-source-modele",
    category: "model",
    uses: ["development", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["Sigstore/cosign", { fr: "Signature Git", en: "Git signing" }],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Altération du modèle avant déploiement",
        attack: "Le modèle ou son code est modifié avant le déploiement.",
        mitigation: "Empreintes, signatures, chaînes de build reproductibles.",
        guard: "AI Guard n’intervient pas dans votre chaîne de build de modèles.",
      },
      en: {
        title: "Model source tampering",
        attack: "The model or its code is modified before deployment.",
        mitigation: "Hashes, signatures, reproducible pipelines.",
        guard: "AI Guard is not part of your model build pipeline.",
      },
    },
  },
  {
    id: "modele-serialise-malveillant",
    category: "model",
    uses: ["development", "models"],
    surface: "model",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["ModelScan", "Fickling"],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Modèle sérialisé malveillant",
        attack: "Un modèle pickle ou PyTorch exécute du code au chargement.",
        mitigation: "Préférer des formats sûrs comme safetensors ; bac à sable ; analyser les modèles.",
        guard: NO_MODEL_SCANNER.fr,
        statusNote: "Parade solide",
      },
      en: {
        title: "Malicious serialised model",
        attack: "A pickle or PyTorch model runs code when it is loaded.",
        mitigation: "Prefer safe formats such as safetensors; sandbox; scan models.",
        guard: NO_MODEL_SCANNER.en,
        statusNote: "Strong mitigation",
      },
    },
  },
  {
    id: "vol-de-modele",
    category: "model",
    uses: ["models"],
    surface: "infra",
    impact: "leak",
    status: "mixed",
    coverage: "no",
    tools: [{ fr: "Pile IAM et sécurité open source", en: "Open-source IAM and security stack" }],
    copy: {
      fr: {
        title: "Vol ou exfiltration de poids",
        attack: "Un attaquant dérobe les poids du modèle sur disque ou dans le cloud.",
        mitigation: "IAM, chiffrement, isolement réseau, journalisation.",
        guard: "Le stockage des poids ne passe pas par AI Guard.",
      },
      en: {
        title: "Model theft and exfiltration",
        attack: "An attacker steals the model’s weights from disk or the cloud.",
        mitigation: "IAM, encryption, network isolation, audit logging.",
        guard: "Weight storage does not go through AI Guard.",
      },
    },
  },
  {
    id: "extraction-par-api",
    category: "model",
    uses: ["models"],
    surface: "model",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: [{ fr: "Passerelles d’API", en: "API gateways" }, { fr: "Limitation de débit", en: "Rate limiting" }],
    owasp: "LLM10",
    releve: "M-04",
    copy: {
      fr: {
        title: "Extraction de modèle par l’API",
        attack: "Des requêtes répétées permettent d’approcher un modèle propriétaire.",
        mitigation: "Limites de débit, contrôle des sorties, détection, recherche sur le tatouage.",
        guard: "La télémétrie de volume existe, mais aucun seuil n’y est réglé contre l’extraction.",
      },
      en: {
        title: "Model extraction via API",
        attack: "Repeated queries approximate a proprietary model.",
        mitigation: "Rate limits, output controls, detection, watermarking research.",
        guard: "Volume telemetry exists, but no threshold is set on it against extraction.",
      },
    },
  },
  {
    id: "inversion-de-modele",
    category: "model",
    uses: ["models"],
    surface: "model",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: ["Opacus", "TensorFlow Privacy"],
    copy: {
      fr: {
        title: "Inversion de modèle",
        attack: "Des propriétés ou des exemples sont retrouvés à partir des sorties du modèle.",
        mitigation: "Confidentialité différentielle ; sorties moins détaillées, sans scores de confiance.",
        guard: MODEL_OUT_OF_SCOPE.fr,
      },
      en: {
        title: "Model inversion",
        attack: "Properties or examples are recovered from the model’s outputs.",
        mitigation: "Differential privacy; less detailed outputs without confidence scores.",
        guard: MODEL_OUT_OF_SCOPE.en,
      },
    },
  },
  {
    id: "inference-appartenance",
    category: "model",
    uses: ["models"],
    surface: "model",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: ["ART", "Opacus"],
    copy: {
      fr: {
        title: "Inférence d’appartenance",
        attack: "Un attaquant détermine si les données d’une personne ont servi à l’entraînement.",
        mitigation: "Confidentialité différentielle, régularisation, sorties limitées.",
        guard: MODEL_OUT_OF_SCOPE.fr,
      },
      en: {
        title: "Membership inference",
        attack: "An attacker works out whether someone’s data was in the training set.",
        mitigation: "Differential privacy, regularisation, limited model outputs.",
        guard: MODEL_OUT_OF_SCOPE.en,
      },
    },
  },

  // --- Attaques adverses -----------------------------------------------------
  {
    id: "exemples-adverses",
    category: "adversarial",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "unsolved",
    coverage: "no",
    tools: ["IBM Adversarial Robustness Toolbox (ART)"],
    releve: "M-05",
    copy: {
      fr: {
        title: "Exemples adverses (évasion)",
        attack: "Une infime perturbation de l’entrée change la classification.",
        mitigation: "Entraînement adverse, prétraitement robuste, ensembles de modèles.",
        guard: MODEL_ROBUSTNESS.fr,
        statusNote: "Dépend du domaine",
      },
      en: {
        title: "Adversarial examples and evasion",
        attack: "A tiny input perturbation changes the classification.",
        mitigation: "Adversarial training, robust preprocessing, ensembles.",
        guard: MODEL_ROBUSTNESS.en,
        statusNote: "Domain-dependent",
      },
    },
  },
  {
    id: "attaque-adverse-physique",
    category: "adversarial",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "no",
    tools: ["ART"],
    copy: {
      fr: {
        title: "Attaque adverse physique",
        attack: "Un autocollant, un patch ou un panneau trompe une caméra ou un modèle.",
        mitigation: "Fusion de capteurs, entraînement adverse, contrôles de robustesse.",
        guard: MODEL_ROBUSTNESS.fr,
      },
      en: {
        title: "Physical adversarial attack",
        attack: "A sticker, patch or sign fools a camera or model.",
        mitigation: "Sensor fusion, adversarial training, robustness checks.",
        guard: MODEL_ROBUSTNESS.en,
      },
    },
  },
  {
    id: "patchs-adverses",
    category: "adversarial",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "no",
    tools: ["ART"],
    copy: {
      fr: {
        title: "Patchs adverses",
        attack: "Un motif ajouté à l’image renverse la décision d’un détecteur ou d’un classifieur.",
        mitigation: "Détection et entraînement robuste.",
        guard: MODEL_ROBUSTNESS.fr,
      },
      en: {
        title: "Adversarial patches",
        attack: "An image patch flips an object detector’s or classifier’s decision.",
        mitigation: "Detection plus robust training.",
        guard: MODEL_ROBUSTNESS.en,
      },
    },
  },
  {
    id: "attaques-par-transfert",
    category: "adversarial",
    uses: ["models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "no",
    tools: ["ART"],
    copy: {
      fr: {
        title: "Attaques par transfert",
        attack: "Une attaque conçue contre un modèle fonctionne aussi sur un autre.",
        mitigation: "Évaluation adverse et ingénierie de la robustesse.",
        guard: MODEL_ROBUSTNESS.fr,
      },
      en: {
        title: "Transfer attacks",
        attack: "An attack crafted against one model also works on another.",
        mitigation: "Adversarial evaluation plus robustness engineering.",
        guard: MODEL_ROBUSTNESS.en,
      },
    },
  },

  // --- Sorties ---------------------------------------------------------------
  {
    id: "sorties-non-maitrisees",
    category: "output",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "partial",
    tools: ["Semgrep", { fr: "Bibliothèques OWASP", en: "OWASP libraries" }],
    owasp: "LLM05",
    releve: "M-13",
    copy: {
      fr: {
        title: "Traitement non sécurisé des sorties",
        attack: "La sortie de l’IA devient directement du SQL, du HTML ou une commande shell.",
        mitigation: "Traiter la sortie du modèle comme une entrée non fiable ; paramétrer ; encoder et valider.",
        guard: "Charges exécutables détectées dans les résultats d’outils (tube vers un shell, eval, script qui exfiltre) ; c’est l’action suivante qui est retenue, pas le résultat.",
      },
      en: {
        title: "Improper output handling",
        attack: "AI output is used directly as SQL, HTML or shell commands.",
        mitigation: "Treat model output as untrusted input; parameterise; encode and validate.",
        guard: "Executable payloads are detected in tool results (a pipe into a shell, eval, an exfiltrating script); the next action is held, not the result itself.",
      },
    },
  },
  {
    id: "code-vulnerable",
    category: "output",
    uses: ["development"],
    surface: "people",
    impact: "compromise",
    status: "mitigated",
    coverage: "partial",
    tools: ["Semgrep", "Bandit"],
    owasp: "LLM05",
    releve: "M-15",
    copy: {
      fr: {
        title: "Code généré vulnérable",
        attack: "Du code ou des commandes générés par l’IA partent sans relecture suffisante et introduisent une faille.",
        mitigation: "Relecture, analyse statique (SAST) en CI, maintien des contrôles de sécurité du projet.",
        guard: "Verdicts SAST tiers reçus et chaînés, audit de dépendances et de secrets attesté en CI ; le code lui-même n’est pas relu par AI Guard.",
      },
      en: {
        title: "Vulnerable generated code",
        attack: "AI-generated code or commands ship without adequate review and introduce a flaw.",
        mitigation: "Code review, static analysis (SAST) in CI, keep the project’s security checks.",
        guard: "Third-party SAST verdicts are received and chained, dependency and secret audits attested in CI; AI Guard does not review the code itself.",
      },
    },
    explainer: {
      fr: {
        definition: "Du code ou une commande proposés par l’IA sont intégrés sans validation suffisante et introduisent une faille dans l’application.",
        example: "Une requête SQL générée assemble directement la saisie utilisateur et ouvre la voie à une injection.",
        reflex: "Relire le code, valider les sorties et conserver les contrôles de sécurité du projet.",
      },
      en: {
        definition: "AI-generated code or commands are integrated without adequate validation, introducing an application vulnerability.",
        example: "A generated SQL query directly joins user input, allowing an injection attack.",
        reflex: "Review code, validate outputs and retain the project’s security checks.",
      },
    },
  },
  {
    id: "injection-sql-via-llm",
    category: "output",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "partial",
    tools: ["SQLAlchemy", { fr: "Droits de base de données", en: "Database permissions" }],
    owasp: "LLM05",
    copy: {
      fr: {
        title: "Injection SQL via le LLM",
        attack: "Le SQL généré par le modèle embarque la saisie de l’attaquant.",
        mitigation: "Requêtes paramétrées et interface de requête restreinte.",
        guard: "Des prédicats déterministes sur les arguments des outils SQL refusent ou font valider une requête destructrice. Une lecture détournée, elle, passe.",
      },
      en: {
        title: "SQL injection via LLM",
        attack: "Model-generated SQL carries the attacker’s input.",
        mitigation: "Parameterised queries and a constrained query interface.",
        guard: "Deterministic predicates on SQL tool arguments deny a destructive query or hold it for approval. A hijacked read still goes through.",
      },
    },
  },
  {
    id: "injection-de-commande",
    category: "output",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "partial",
    tools: ["seccomp", CONTAINERS],
    owasp: "LLM05",
    copy: {
      fr: {
        title: "Injection de commande",
        attack: "L’IA génère et exécute des commandes shell.",
        mitigation: "Éviter le shell ; API en liste blanche ; bac à sable.",
        guard: "Chaque commande est classée selon ses arguments : hors de la liste de lecture, elle compte comme irréversible et attend une validation humaine. Aucun bac à sable n’est fourni.",
      },
      en: {
        title: "Command injection",
        attack: "The AI generates and runs shell commands.",
        mitigation: "Avoid shells; allowlisted APIs; sandboxing.",
        guard: "Each command is classified by its arguments: outside the read list it counts as irreversible and waits for human approval. No sandbox is provided.",
      },
    },
  },
  {
    id: "xss-contenu-genere",
    category: "output",
    uses: ["development"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["DOMPurify", "OWASP Java Encoder"],
    owasp: "LLM05",
    copy: {
      fr: {
        title: "XSS par contenu généré",
        attack: "Le HTML ou le Markdown généré contient du JavaScript malveillant.",
        mitigation: "Encodage et assainissement des sorties selon leur contexte.",
        guard: "L’affichage des réponses relève de votre application ; AI Guard ne les assainit pas.",
      },
      en: {
        title: "XSS from generated content",
        attack: "Generated HTML or Markdown carries malicious JavaScript.",
        mitigation: "Context-aware output encoding and sanitisation.",
        guard: "Rendering responses is your application’s job; AI Guard does not sanitise them.",
      },
    },
  },
  {
    id: "ssrf-via-agent",
    category: "output",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: [{ fr: "Pare-feu et proxys", en: "Firewalls and proxies" }, "OPA"],
    copy: {
      fr: {
        title: "SSRF par un agent",
        attack: "Un navigateur ou un outil de l’IA atteint des adresses internes ou le service de métadonnées cloud.",
        mitigation: "Liste blanche de sortie, isolement réseau, validation des URL.",
        guard: "Aucun filtrage réseau des outils en aval : seule une règle de policy écrite sur l’argument peut retenir une URL.",
      },
      en: {
        title: "SSRF through agents",
        attack: "An AI browser or tool reaches internal addresses or the cloud metadata service.",
        mitigation: "Egress allowlist, network isolation, URL validation.",
        guard: "No network filtering of downstream tools: only a policy rule written on the argument can hold a URL.",
      },
    },
  },
  {
    id: "traversee-de-chemin",
    category: "output",
    uses: ["development", "agents"],
    surface: "actions",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: [{ fr: "Codage sécurisé standard", en: "Standard secure coding" }],
    copy: {
      fr: {
        title: "Traversée de répertoire",
        attack: "Un nom de fichier produit par l’agent atteint un fichier non prévu.",
        mitigation: "Canonisation des chemins et répertoires cloisonnés.",
        guard: "AI Guard ne canonise pas les chemins ; seule une règle de policy écrite à la main peut refuser un motif.",
      },
      en: {
        title: "Path traversal",
        attack: "An agent-generated file name reaches an unintended file.",
        mitigation: "Canonicalisation plus sandboxed directories.",
        guard: "AI Guard does not canonicalise paths; only a hand-written policy rule can refuse a pattern.",
      },
    },
  },

  // --- Confidentialité ---------------------------------------------------------
  {
    id: "fuite-de-donnees",
    category: "privacy",
    uses: ["development", "workplace", "agents", "models"],
    surface: "data",
    impact: "leak",
    status: "mixed",
    coverage: "partial",
    tools: ["Microsoft Presidio"],
    owasp: "LLM02",
    releve: "M-10",
    copy: {
      fr: {
        title: "Divulgation d’informations sensibles",
        attack: "L’IA divulgue des données personnelles, des identifiants ou des secrets.",
        mitigation: "Minimisation des données, DLP, filtrage, contrôle d’accès.",
        guard: "DLP en sortie du proxy LLM : secrets bloqués, données personnelles signalées, masquage en option. Après un contenu suspect, l’exfiltration dans les arguments d’une action est bloquée. Les réponses ne sont pas filtrées.",
      },
      en: {
        title: "Sensitive information disclosure",
        attack: "The AI discloses personal data, credentials or secrets.",
        mitigation: "Data minimisation, DLP, filtering, access control.",
        guard: "DLP on the LLM proxy’s egress: secrets blocked, personal data flagged, redaction optional. After suspicious content, exfiltration in an action’s arguments is blocked. Responses are not filtered.",
      },
    },
    explainer: {
      fr: {
        definition: "Une information confidentielle est transmise à un service IA non autorisé ou ressort dans une réponse accessible à une personne non autorisée.",
        example: "Un collaborateur joint un fichier client à un assistant non autorisé ; un assistant cite les coordonnées d’un client à une personne qui n’a pas à les connaître.",
        reflex: "Réduire les données transmises et vérifier les destinataires autorisés.",
      },
      en: {
        definition: "Confidential information is sent to an unauthorised AI service or appears in a response available to someone without permission.",
        example: "An employee attaches a customer file to an unapproved assistant; an assistant quotes a customer’s details to someone who has no need to know them.",
        reflex: "Minimise shared data and check who is allowed to receive it.",
      },
    },
  },
  {
    id: "fuite-dans-les-journaux",
    category: "privacy",
    uses: ["development", "agents"],
    surface: "infra",
    impact: "leak",
    status: "solved",
    coverage: "yes",
    tools: ["Presidio", { fr: "Filtres OpenTelemetry", en: "OpenTelemetry filters" }],
    owasp: "LLM02",
    copy: {
      fr: {
        title: "Prompts et secrets dans les journaux",
        attack: "Des prompts et des secrets finissent stockés dans les outils d’observabilité ou de traces.",
        mitigation: "Masquage, journalisation restreinte, chiffrement.",
        guard: "Pour ce qui transite par AI Guard : ni contenu d’argument ni secret journalisé, seulement des métadonnées et des empreintes ; les instructions système sont écartées à l’ingestion des traces.",
      },
      en: {
        title: "Prompt leakage in logs",
        attack: "Prompts and secrets end up stored in observability or tracing systems.",
        mitigation: "Redaction, restricted logging, encryption.",
        guard: "For what passes through AI Guard: no argument content or secret is logged, only metadata and hashes; system instructions are dropped when traces are ingested.",
      },
    },
  },
  {
    id: "fuite-de-secrets",
    category: "privacy",
    uses: ["development", "workplace"],
    surface: "prompt",
    impact: "leak",
    status: "solved",
    coverage: "yes",
    tools: ["Gitleaks", "TruffleHog"],
    owasp: "LLM02",
    releve: "M-14",
    copy: {
      fr: {
        title: "Fuite de secrets",
        attack: "Des utilisateurs collent des clés d’API, des mots de passe ou du code source dans un prompt.",
        mitigation: "Détection des secrets avant l’envoi.",
        guard: "Secret Guard bloque localement le prompt qui contient un secret (Copilot, Claude Code, Codex) ; la DLP du proxy bloque les secrets sortants ; les accès restent au coffre.",
      },
      en: {
        title: "Secret leakage",
        attack: "Users paste API keys, passwords or source code into a prompt.",
        mitigation: "Secret detection before submission.",
        guard: "Secret Guard blocks a prompt containing a secret locally (Copilot, Claude Code, Codex); the proxy’s DLP blocks outgoing secrets; credentials stay in the vault.",
      },
    },
  },
  {
    id: "memorisation-entrainement",
    category: "privacy",
    uses: ["models"],
    surface: "model",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: ["Opacus", "Presidio"],
    owasp: "LLM02",
    copy: {
      fr: {
        title: "Mémorisation des données d’entraînement",
        attack: "Le modèle recrache des exemples confidentiels vus à l’entraînement.",
        mitigation: "Dédoublonnage, entraînement confidentiel, confidentialité différentielle, filtres de sortie.",
        guard: "Les réponses du modèle ne sont pas filtrées par AI Guard.",
      },
      en: {
        title: "Training-data memorisation",
        attack: "The model repeats confidential examples seen during training.",
        mitigation: "Deduplication, private training, differential privacy, output filters.",
        guard: "AI Guard does not filter model responses.",
      },
    },
  },
  {
    id: "inference-attributs-sensibles",
    category: "privacy",
    uses: ["workplace", "models"],
    surface: "model",
    impact: "leak",
    status: "mitigated",
    coverage: "no",
    tools: ["ART", { fr: "Outils de confidentialité", en: "Privacy tooling" }],
    owasp: "LLM02",
    copy: {
      fr: {
        title: "Inférence d’attributs sensibles",
        attack: "L’IA déduit des attributs qui n’ont jamais été communiqués.",
        mitigation: "Minimisation des données, sorties restreintes, tests de confidentialité.",
        guard: "AI Guard n’évalue pas le comportement du modèle.",
      },
      en: {
        title: "Inference of sensitive attributes",
        attack: "The AI infers attributes that were never disclosed.",
        mitigation: "Data minimisation, restricted outputs, privacy testing.",
        guard: "AI Guard does not evaluate model behaviour.",
      },
    },
  },

  // --- Chaîne d'approvisionnement ----------------------------------------------
  {
    id: "depot-de-modeles-compromis",
    category: "supply",
    uses: ["development", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["ModelScan", "Fickling", "Sigstore"],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Dépôt de modèles compromis",
        attack: "Un modèle malveillant est publié sur un hub de modèles.",
        mitigation: "Vérifier l’éditeur, l’empreinte et la signature ; analyser l’artefact.",
        guard: NO_MODEL_SCANNER.fr,
      },
      en: {
        title: "Compromised model repository",
        attack: "A malicious model is uploaded to a model hub.",
        mitigation: "Verify publisher, hash and signature; scan the artefact.",
        guard: NO_MODEL_SCANNER.en,
      },
    },
  },
  {
    id: "dependances-compromises",
    category: "supply",
    uses: ["development", "agents", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "partial",
    tools: ["Syft", "Grype", "Trivy", "osv-scanner"],
    owasp: "LLM03",
    releve: "M-11",
    copy: {
      fr: {
        title: "Dépendances compromises",
        attack: "Une dépendance Python ou npm malveillante atteint la pile IA.",
        mitigation: "Fichiers de verrouillage, SBOM, signature, analyse.",
        guard: "SBOM et audit de dépendances en CI, attestés ; les outils MCP sont empreintés et mis en quarantaine s’ils changent.",
      },
      en: {
        title: "Dependency compromise",
        attack: "A malicious Python or npm dependency reaches the AI stack.",
        mitigation: "Lockfiles, SBOM, signing, scanning.",
        guard: "SBOM and dependency audits in CI, attested; MCP tools are fingerprinted and quarantined if they change.",
      },
    },
    explainer: {
      fr: {
        definition: "Une bibliothèque, un modèle ou un composant tiers introduit une vulnérabilité ou un comportement malveillant dans la chaîne IA.",
        example: "Une équipe importe un modèle depuis un dépôt imitant celui de son fournisseur habituel.",
        reflex: "Vérifier l’origine et l’intégrité des composants, puis suivre leurs versions et vulnérabilités.",
      },
      en: {
        definition: "A third-party library, model or component introduces a vulnerability or malicious behaviour into the AI supply chain.",
        example: "A team imports a model from a repository impersonating its usual supplier.",
        reflex: "Check component provenance and integrity, then track versions and vulnerabilities.",
      },
    },
  },
  {
    id: "typosquatting",
    category: "supply",
    uses: ["development"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "partial",
    tools: [{ fr: "Contrôles pip et npm", en: "pip and npm controls" }, { fr: "Analyseurs de dépendances", en: "Dependency scanners" }],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Typosquatting et confusion de dépendances",
        attack: "Un attaquant publie une bibliothèque IA au nom presque identique.",
        mitigation: "Registre interne, contrôle des espaces de noms, fichiers de verrouillage.",
        guard: "Un serveur MCP homonyme ne passe pas : tout outil nouveau reste en quarantaine jusqu’à approbation. Les paquets Python et npm ne sont pas contrôlés.",
      },
      en: {
        title: "Typosquatting and dependency confusion",
        attack: "An attacker publishes an AI library with a near-identical name.",
        mitigation: "Internal registry, namespace controls, lockfiles.",
        guard: "A lookalike MCP server does not get through: every new tool stays quarantined until approved. Python and npm packages are not checked.",
      },
    },
  },
  {
    id: "framework-compromis",
    category: "supply",
    uses: ["development", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["Sigstore", { fr: "Outillage SLSA", en: "SLSA tooling" }],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Framework d’entraînement compromis",
        attack: "PyTorch, une bibliothèque ou la chaîne d’outils sont altérés.",
        mitigation: "Builds de confiance, empreintes, SBOM, artefacts signés.",
        guard: "AI Guard n’intervient pas dans votre chaîne d’entraînement.",
      },
      en: {
        title: "Compromised training framework",
        attack: "PyTorch, a library or the toolchain is altered.",
        mitigation: "Trusted builds, hashes, SBOM, signed artefacts.",
        guard: "AI Guard is not part of your training toolchain.",
      },
    },
  },
  {
    id: "format-de-modele-dangereux",
    category: "supply",
    uses: ["development", "models"],
    surface: "model",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["ModelScan", "Fickling"],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Format de modèle dangereux",
        attack: "Un format de type pickle embarque une charge exécutable.",
        mitigation: "Safetensors ou une autre représentation non exécutable.",
        guard: NO_MODEL_SCANNER.fr,
      },
      en: {
        title: "Unsafe model format",
        attack: "A pickle-like format embeds an executable payload.",
        mitigation: "Safetensors or another non-executable representation.",
        guard: NO_MODEL_SCANNER.en,
      },
    },
  },

  // --- Infrastructure --------------------------------------------------------
  {
    id: "vol-identifiants-cloud",
    category: "infra",
    uses: ["development", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["OpenBao / Vault", { fr: "Outillage des secrets Kubernetes", en: "Kubernetes secrets tooling" }],
    copy: {
      fr: {
        title: "Vol d’identifiants GPU ou cloud",
        attack: "Un notebook compromis expose des identifiants cloud.",
        mitigation: "Identité de charge de travail, identifiants de courte durée, coffre à secrets.",
        guard: "Vos notebooks et votre cloud ne passent pas par AI Guard.",
      },
      en: {
        title: "GPU and cloud credential theft",
        attack: "A compromised notebook exposes cloud credentials.",
        mitigation: "Workload identity, short-lived credentials, a secret vault.",
        guard: "Your notebooks and cloud do not go through AI Guard.",
      },
    },
  },
  {
    id: "vol-cle-api-ia",
    category: "infra",
    uses: ["development", "agents"],
    surface: "infra",
    impact: "leak",
    status: "solved",
    coverage: "partial",
    tools: ["OpenBao / Vault", "Gitleaks", "TruffleHog"],
    copy: {
      fr: {
        title: "Vol de clé d’API IA",
        attack: "Une clé fuit par le code, les journaux ou le modèle.",
        mitigation: "Gestion des secrets, rotation des clés, portées limitées.",
        guard: "Les clés sont bloquées dans les prompts et en sortie du proxy, jamais stockées ni journalisées par AI Guard ; la rotation et l’analyse de vos dépôts restent chez vous.",
      },
      en: {
        title: "AI API key theft",
        attack: "A key leaks through code, logs or the model.",
        mitigation: "Secret management, key rotation, scope limits.",
        guard: "Keys are blocked in prompts and on proxy egress, never stored or logged by AI Guard; rotation and scanning your repositories stay with you.",
      },
    },
  },
  {
    id: "serveur-inference-compromis",
    category: "infra",
    uses: ["models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["Trivy", "Falco", "Kubernetes"],
    copy: {
      fr: {
        title: "Serveur d’inférence compromis",
        attack: "Une vulnérabilité de la pile de service du modèle est exploitée.",
        mitigation: "Gestion des correctifs, isolement des conteneurs, authentification.",
        guard: "L’exploitation de vos serveurs d’inférence reste hors du périmètre d’AI Guard.",
      },
      en: {
        title: "Inference-server compromise",
        attack: "A vulnerability in the model-serving stack is exploited.",
        mitigation: "Patch management, container isolation, authentication.",
        guard: "Running your inference servers stays outside AI Guard’s scope.",
      },
    },
  },
  {
    id: "evasion-de-conteneur",
    category: "infra",
    uses: ["agents", "models"],
    surface: "infra",
    impact: "compromise",
    status: "mixed",
    coverage: "no",
    tools: ["Docker", "Kata Containers", "gVisor"],
    copy: {
      fr: {
        title: "Évasion de conteneur",
        attack: "Un modèle ou du code malveillant s’échappe de son bac à sable.",
        mitigation: "seccomp, espaces de noms, isolement par VM.",
        guard: "AI Guard ne fournit pas de bac à sable d’exécution.",
      },
      en: {
        title: "Container escape and runtime exploit",
        attack: "A malicious model or code escapes its sandbox.",
        mitigation: "seccomp, namespaces, VM isolation.",
        guard: "AI Guard does not provide an execution sandbox.",
      },
    },
  },
  {
    id: "notebook-compromis",
    category: "infra",
    uses: ["development", "models"],
    surface: "infra",
    impact: "compromise",
    status: "solved",
    coverage: "no",
    tools: ["JupyterHub", CONTAINERS],
    copy: {
      fr: {
        title: "Notebook compromis",
        attack: "Un serveur Jupyter permet d’exécuter du code arbitraire.",
        mitigation: "Authentification, isolement réseau, bac à sable par utilisateur.",
        guard: "Vos notebooks ne passent pas par AI Guard.",
      },
      en: {
        title: "Notebook compromise",
        attack: "A Jupyter server allows arbitrary code execution.",
        mitigation: "Authentication, network isolation, per-user sandbox.",
        guard: "Your notebooks do not go through AI Guard.",
      },
    },
  },

  // --- Disponibilité & coûts -------------------------------------------------
  {
    id: "deni-de-service-modele",
    category: "availability",
    uses: ["agents", "models"],
    surface: "prompt",
    impact: "cost",
    status: "solved",
    coverage: "partial",
    tools: ["NGINX", "Envoy", "Kong"],
    owasp: "LLM10",
    copy: {
      fr: {
        title: "Déni de service du modèle",
        attack: "Des prompts extrêmement coûteux saturent le modèle.",
        mitigation: "Quotas, limites de débit, plafonds de taille et de jetons.",
        guard: "Quota de requêtes par minute et par client sur le proxy LLM ; aucune limite de jetons par requête.",
      },
      en: {
        title: "Model denial of service",
        attack: "Extremely costly prompts saturate the model.",
        mitigation: "Quotas, rate limits, request-size and token limits.",
        guard: "A per-tenant requests-per-minute quota on the LLM proxy; no per-request token limit.",
      },
    },
  },
  {
    id: "deni-de-portefeuille",
    category: "availability",
    uses: ["workplace", "agents", "models"],
    surface: "prompt",
    impact: "cost",
    status: "solved",
    coverage: "partial",
    tools: [{ fr: "Passerelles d’API", en: "API gateways" }, { fr: "Suivi de facturation", en: "Billing monitors" }],
    owasp: "LLM10",
    copy: {
      fr: {
        title: "Déni de portefeuille",
        attack: "Un attaquant fait délibérément exploser la facture d’API ou de cloud.",
        mitigation: "Budgets et limites par utilisateur ; alertes de dépense.",
        guard: "Quota par minute sur le proxy et coût suivi par agent ; aucun plafond de dépense ni alerte budgétaire.",
      },
      en: {
        title: "Denial of wallet",
        attack: "An attacker deliberately runs up a large API or cloud bill.",
        mitigation: "Per-user budgets and rate limits; spend alerts.",
        guard: "A per-minute proxy quota and cost tracked per agent; no spending cap or budget alert.",
      },
    },
  },
  {
    id: "complexite-algorithmique",
    category: "availability",
    uses: ["models"],
    surface: "prompt",
    impact: "cost",
    status: "solved",
    coverage: "no",
    tools: [{ fr: "Contrôles de passerelle standard", en: "Standard gateway controls" }],
    owasp: "LLM10",
    copy: {
      fr: {
        title: "Attaques par complexité algorithmique",
        attack: "Des entrées sont conçues pour maximiser la charge d’inférence.",
        mitigation: "Plafonds de jetons et de taille d’entrée, délais.",
        guard: "AI Guard ne pose ni plafond de jetons ni délai d’inférence.",
      },
      en: {
        title: "Algorithmic complexity attacks",
        attack: "Inputs are crafted to maximise the inference workload.",
        mitigation: "Token and input limits, timeouts.",
        guard: "AI Guard sets no token cap and no inference timeout.",
      },
    },
  },
  {
    id: "epuisement-gpu",
    category: "availability",
    uses: ["models"],
    surface: "infra",
    impact: "cost",
    status: "solved",
    coverage: "no",
    tools: ["Kubernetes"],
    owasp: "LLM10",
    copy: {
      fr: {
        title: "Épuisement des ressources GPU",
        attack: "Des tâches malveillantes accaparent tous les accélérateurs.",
        mitigation: "Quotas Kubernetes et limites d’ordonnancement.",
        guard: "L’ordonnancement de vos GPU reste hors du périmètre d’AI Guard.",
      },
      en: {
        title: "GPU resource exhaustion",
        attack: "Malicious jobs grab every accelerator.",
        mitigation: "Kubernetes quotas and scheduling limits.",
        guard: "Scheduling your GPUs stays outside AI Guard’s scope.",
      },
    },
  },

  // --- Intégrité & confiance -------------------------------------------------
  {
    id: "hallucinations",
    category: "integrity",
    uses: ["development", "workplace", "agents", "models"],
    surface: "model",
    impact: "manipulation",
    status: "mitigated",
    coverage: "partial",
    tools: ["Giskard", { fr: "Frameworks d’évaluation", en: "Eval frameworks" }],
    owasp: "LLM09",
    releve: "M-16",
    copy: {
      fr: {
        title: "Hallucinations exploitées",
        attack: "Un attaquant compte sur la confiance accordée à une information inventée.",
        mitigation: "Ancrage dans des sources, recherche, vérification, approbation avant d’agir.",
        guard: "L’hallucination n’est pas mesurée ; une action irréversible décidée sur un fait inventé attend quand même une validation humaine, attestée dans l’Evidence Pack.",
        statusNote: "Pas entièrement résolu",
      },
      en: {
        title: "Hallucination exploitation",
        attack: "An attacker counts on fabricated information being trusted.",
        mitigation: "Grounding, retrieval, verification, approval before acting.",
        guard: "Hallucination is not measured; an irreversible action based on an invented fact still waits for human approval, attested in the Evidence Pack.",
        statusNote: "Not fully solved",
      },
    },
    explainer: {
      fr: {
        definition: "L’IA produit une réponse convaincante mais inexacte. Le risque augmente si cette réponse est utilisée sans vérification.",
        example: "Une synthèse invente un chiffre que le collaborateur reprend dans une présentation client.",
        reflex: "Vérifier les faits dans les sources et faire relire les décisions importantes par une personne compétente.",
      },
      en: {
        definition: "AI produces a convincing but inaccurate answer. The risk grows when that answer is used without verification.",
        example: "A summary invents a number that an employee copies into a customer presentation.",
        reflex: "Check facts against their sources and have important decisions reviewed by a qualified person.",
      },
    },
  },
  {
    id: "fausses-citations",
    category: "integrity",
    uses: ["development", "workplace"],
    surface: "model",
    impact: "manipulation",
    status: "mixed",
    coverage: "no",
    tools: [{ fr: "Validateurs sur mesure", en: "Custom validators" }],
    owasp: "LLM09",
    copy: {
      fr: {
        title: "Fausses citations",
        attack: "Le modèle invente des URL ou des sources.",
        mitigation: "Résoudre et vérifier les sources citées par programme.",
        guard: "AI Guard ne vérifie pas les sources citées dans les réponses.",
      },
      en: {
        title: "Fake citations",
        attack: "The model invents URLs or sources.",
        mitigation: "Resolve and verify cited sources programmatically.",
        guard: "AI Guard does not verify the sources cited in responses.",
      },
    },
  },
  {
    id: "manipulation-base-de-connaissances",
    category: "integrity",
    uses: ["workplace", "models"],
    surface: "data",
    impact: "manipulation",
    status: "solved",
    coverage: "no",
    tools: ["Sigstore", { fr: "Contrôles sur mesure", en: "Custom controls" }],
    copy: {
      fr: {
        title: "Manipulation de la base de connaissances",
        attack: "Un attaquant modifie une source d’information qui fait autorité.",
        mitigation: "Données signées, provenance, pondération des sources.",
        guard: "La provenance des corpus est déclarée, mais une modification de la source n’est pas détectée.",
      },
      en: {
        title: "Knowledge-base manipulation",
        attack: "An attacker changes an authoritative source of information.",
        mitigation: "Signed data, provenance, source weighting.",
        guard: "Corpus provenance is declared, but a change to the source is not detected.",
      },
    },
  },

  // --- Abus humains ------------------------------------------------------------
  {
    id: "phishing-augmente",
    category: "human",
    uses: ["workplace", "agents"],
    surface: "people",
    impact: "fraud",
    status: "mitigated",
    coverage: "partial",
    tools: ["SpamAssassin"],
    releve: "M-07",
    copy: {
      fr: {
        title: "Phishing augmenté par l’IA",
        attack: "L’IA produit à grande échelle une ingénierie sociale personnalisée.",
        mitigation: "Sécurité de la messagerie, DMARC, vérification des utilisateurs, détection d’anomalies.",
        guard: "Votre agent ne peut pas devenir l’émetteur : un envoi hors de la liste autorisée est bloqué. La réception reste à votre passerelle de messagerie.",
      },
      en: {
        title: "AI-enhanced phishing",
        attack: "AI produces personalised social engineering at scale.",
        mitigation: "Email security, DMARC, user verification, anomaly detection.",
        guard: "Your agent cannot become the sender: a send outside the allowlist is blocked. Inbound mail stays with your email gateway.",
      },
    },
  },
  {
    id: "usurpation-deepfake",
    category: "human",
    uses: ["workplace"],
    surface: "people",
    impact: "fraud",
    status: "mitigated",
    coverage: "partial",
    tools: ["C2PA"],
    releve: "M-08",
    copy: {
      fr: {
        title: "Usurpation par deepfake",
        attack: "Un faux audio ou une fausse vidéo sert à frauder ou à contourner une authentification.",
        mitigation: "Authentification hors bande, détection du vivant, provenance cryptographique.",
        guard: "Le faux dirigeant ne peut pas approuver : décision signée, attribuée, en séparation des devoirs. Le média truqué, lui, n’est pas détecté.",
      },
      en: {
        title: "Deepfake impersonation",
        attack: "Fake audio or video is used for fraud or to bypass authentication.",
        mitigation: "Out-of-band authentication, liveness checks, cryptographic provenance.",
        guard: "A fake executive cannot approve: decisions are signed, attributed and segregated. The fake media itself is not detected.",
      },
    },
  },
  {
    id: "fraude-voix-clonee",
    category: "human",
    uses: ["workplace"],
    surface: "people",
    impact: "fraud",
    status: "solved",
    coverage: "partial",
    tools: [{ fr: "MFA standard", en: "Standard MFA" }],
    releve: "M-08",
    copy: {
      fr: {
        title: "Fraude à la voix clonée",
        attack: "Une voix de synthèse imite un collaborateur ou un proche.",
        mitigation: "Ne jamais accepter une voix seule comme authentification.",
        guard: "Une approbation exige une identité authentifiée, jamais une voix ; la voix clonée elle-même n’est pas détectée.",
      },
      en: {
        title: "Voice cloning fraud",
        attack: "A synthetic voice impersonates an employee or a relative.",
        mitigation: "Never accept a voice alone as authentication.",
        guard: "An approval requires an authenticated identity, never a voice; the cloned voice itself is not detected.",
      },
    },
  },
  {
    id: "malware-genere",
    category: "human",
    uses: ["development"],
    surface: "infra",
    impact: "compromise",
    status: "mitigated",
    coverage: "no",
    tools: ["YARA", "Sigma", "Suricata", "ClamAV"],
    releve: "M-09",
    copy: {
      fr: {
        title: "Malware généré par IA",
        attack: "L’IA réduit l’effort nécessaire pour écrire ou modifier du code malveillant.",
        mitigation: "Détection endpoint et réseau existante, surveillance des abus.",
        guard: "Plan endpoint et poste de travail : le SOC du client. Une passerelle d’actions ne voit pas le poste.",
      },
      en: {
        title: "AI-generated malware",
        attack: "AI lowers the effort needed to write or modify malicious code.",
        mitigation: "Existing endpoint and network detection, plus abuse monitoring.",
        guard: "The endpoint and workstation plane belongs to the customer’s SOC. An action gateway does not see the endpoint.",
      },
    },
  },
  {
    id: "decouverte-vulnerabilites",
    category: "human",
    uses: ["development"],
    surface: "infra",
    impact: "compromise",
    status: "mitigated",
    coverage: "no",
    tools: ["Nuclei", "Wazuh", "Suricata"],
    copy: {
      fr: {
        title: "Découverte automatisée de vulnérabilités",
        attack: "L’IA accélère la reconnaissance et l’exploitation.",
        mitigation: "Gestion de la surface d’attaque, IDS, correctifs.",
        guard: "Relève de votre SOC et de votre gestion des vulnérabilités.",
      },
      en: {
        title: "Automated vulnerability discovery abuse",
        attack: "AI speeds up reconnaissance and exploitation.",
        mitigation: "Attack-surface management, IDS, patching.",
        guard: "This belongs to your SOC and vulnerability management.",
      },
    },
  },

  // --- Gouvernance -----------------------------------------------------------
  {
    id: "shadow-ai",
    category: "governance",
    uses: ["development", "workplace"],
    surface: "people",
    impact: "leak",
    status: "solved",
    coverage: "partial",
    tools: [{ fr: "Surveillance DNS et proxy", en: "DNS and proxy monitoring" }, "DLP"],
    releve: "M-10",
    copy: {
      fr: {
        title: "Shadow AI",
        attack: "Des collaborateurs envoient des données de l’entreprise vers des outils IA non autorisés.",
        mitigation: "Inventaire des applications, contrôles sur les postes, services approuvés.",
        guard: "Inventaire dérivé d’un extrait de journal que vous déposez, sans capteur réseau ; Secret Guard protège les assistants de code configurés. L’usage web personnel n’est pas couvert.",
      },
      en: {
        title: "Shadow AI",
        attack: "Employees send company data to unapproved AI tools.",
        mitigation: "Application inventory, endpoint controls, approved services.",
        guard: "An inventory derived from a log extract you upload, with no network sensor; Secret Guard protects configured coding assistants. Personal web use is not covered.",
      },
    },
  },
  {
    id: "provenance-modele-inconnue",
    category: "governance",
    uses: ["development", "models"],
    surface: "model",
    impact: "oversight",
    status: "solved",
    coverage: "partial",
    tools: ["CycloneDX"],
    owasp: "LLM03",
    copy: {
      fr: {
        title: "Provenance de modèle inconnue",
        attack: "L’organisation ignore l’origine, les données ou la version de ses modèles.",
        mitigation: "Inventaire IA et ML, provenance, SBOM et ML-BOM.",
        guard: "Fournisseur et modèle relevés à chaque appel supervisé, provenance des corpus déclarée ; aucun ML-BOM des poids.",
      },
      en: {
        title: "Unknown model provenance",
        attack: "The organisation cannot tell where a model comes from, what data it saw or which version runs.",
        mitigation: "AI and ML inventory, provenance, SBOM and ML-BOM.",
        guard: "Provider and model are recorded on every supervised call and corpus provenance is declared; there is no ML-BOM for weights.",
      },
    },
  },
  {
    id: "red-teaming-insuffisant",
    category: "governance",
    uses: ["development", "models"],
    surface: "model",
    impact: "oversight",
    status: "solved",
    coverage: "no",
    tools: ["garak", "PyRIT", "Promptfoo", "Giskard"],
    copy: {
      fr: {
        title: "Red teaming IA insuffisant",
        attack: "Les vulnérabilités ne sont découvertes qu’après le déploiement.",
        mitigation: "Évaluation adverse continue dans la CI/CD.",
        guard: "AI Guard n’évalue pas vos modèles ; ses propres garanties sont prouvées par des scénarios rejoués en CI.",
      },
      en: {
        title: "Insufficient AI red teaming",
        attack: "Vulnerabilities are found only after deployment.",
        mitigation: "Continuous adversarial evaluation in CI/CD.",
        guard: "AI Guard does not test your models; its own guarantees are proven by scenarios replayed in CI.",
      },
    },
  },
  {
    id: "derive-de-modele",
    category: "governance",
    uses: ["development", "agents", "models"],
    surface: "model",
    impact: "manipulation",
    status: "solved",
    coverage: "no",
    tools: ["Promptfoo", "garak", "Giskard"],
    copy: {
      fr: {
        title: "Dérive ou régression de sécurité du modèle",
        attack: "Une nouvelle version du modèle ou du prompt réintroduit des vulnérabilités.",
        mitigation: "Suite de non-régression de sécurité avant chaque mise en production.",
        guard: "Les contrôles d’action ne dépendent pas du modèle, mais AI Guard ne signale pas un changement de version.",
      },
      en: {
        title: "Model drift and security regression",
        attack: "A new model or prompt version brings vulnerabilities back.",
        mitigation: "A security regression suite before every release.",
        guard: "Action controls do not depend on the model, but AI Guard does not flag a version change.",
      },
    },
  },
  {
    id: "actions-non-tracables",
    category: "governance",
    uses: ["workplace", "agents"],
    surface: "actions",
    impact: "oversight",
    status: "solved",
    coverage: "yes",
    tools: ["Sigstore Rekor", "OpenTelemetry"],
    copy: {
      fr: {
        title: "Actions d’agent non traçables",
        attack: "Personne ne peut prouver après coup ce que l’agent a fait, pourquoi, ni qui l’a approuvé ; les journaux sont réécrivables.",
        mitigation: "Journaux en ajout seul et infalsifiables, décisions signées, preuves exportables.",
        guard: "Journal d’audit en ajout seul, chaîné par empreintes et vérifiable ; exports AI Act et RGPD.",
      },
      en: {
        title: "Untraceable agent actions",
        attack: "Nobody can prove afterwards what the agent did, why, or who approved it; logs can be rewritten.",
        mitigation: "Append-only, tamper-evident logs; signed decisions; exportable evidence.",
        guard: "An append-only, hash-chained and verifiable audit log; AI Act and GDPR exports.",
      },
    },
  },
];

export const GLOSSARY_COPY = {
  fr: {
    title: "Glossaire des menaces IA",
    description: "Le glossaire opérationnel des menaces cyber de l’IA : attaque type, parade de référence, outils libres, état de l’art et couverture AI Guard, filtrables par usage, surface d’attaque et impact.",
    kicker: "COMPRENDRE LES RISQUES",
    intro: "Trouvez la menace IA qui vous concerne et découvrez la réponse adaptée : l’attaque type, la parade de référence, les outils libres et ce que couvre AI Guard.",
    home: "Accueil",
    search: "Rechercher une menace",
    placeholder: "Ex. : injection, secrets, garak, RAG…",
    sort: "Trier par",
    sorts: { category: "Catégorie", risk: "Non résolu d’abord", coverage: "Couverture AI Guard", name: "Nom (A → Z)" },
    filter: "Filtrer par usage IA",
    all: "Tous les usages",
    uses: { development: "Développeurs", workplace: "Collaborateurs", agents: "Agents", models: "AI scientist" },
    coverageFilter: "Filtrer par couverture AI Guard",
    coverageAll: "Toutes",
    coverage: { yes: "Couvert", partial: "Partiel", no: "Non couvert" },
    coverageLegend: "Couvert : un contrôle livré bloque ou retient l’action sur le chemin supervisé. Partiel : il détecte, orchestre un outil tiers, atteste une mesure ou ne tient qu’une facette. Non couvert : aucun contrôle AI Guard.",
    category: "Catégorie",
    categoryAll: "Toutes les catégories",
    categories: {
      prompt: "Prompts & instructions",
      agents: "Agents",
      rag: "RAG",
      model: "Modèle & entraînement",
      adversarial: "Attaques adverses",
      output: "Sorties",
      privacy: "Confidentialité",
      supply: "Chaîne d’approvisionnement",
      infra: "Infrastructure",
      availability: "Disponibilité & coûts",
      integrity: "Intégrité & confiance",
      human: "Abus humains",
      governance: "Gouvernance",
    },
    surface: "Surface d’attaque",
    surfaceAll: "Toutes les surfaces",
    surfaces: {
      prompt: "Prompt",
      data: "Données & contexte",
      model: "Modèle & poids",
      actions: "Actions & outils",
      people: "Humains",
      infra: "Infra & dépendances",
    },
    impact: "Impact",
    impactAll: "Tous les impacts",
    impacts: {
      leak: "Fuite de données",
      manipulation: "Réponse manipulée",
      action: "Action non autorisée",
      compromise: "Compromission technique",
      cost: "Panne & coûts",
      fraud: "Fraude",
      oversight: "Perte de contrôle",
    },
    status: "État de l’art",
    statusAll: "Tous les états",
    statuses: { unsolved: "Non résolu", mitigated: "Atténué", mixed: "Selon le contexte", solved: "Maîtrisé" },
    columns: {
      threat: "Menace",
      visual: "Aperçu",
      attack: "Attaque type · conséquence",
      mitigation: "Parade de référence",
      tools: "Outils libres",
      status: "État de l’art",
      guard: "AI Guard",
    },
    tableHeading: "Tableau des menaces",
    caption: "Menaces cyber de l’IA : attaque type, parade de référence, outils libres, état de l’art et couverture AI Guard. Chaque nom de menace ouvre son détail.",
    count: "menaces affichées",
    countOne: "menace affichée",
    of: "sur",
    emptyTitle: "Aucune menace trouvée",
    emptyText: "Essayez un autre mot ou élargissez les filtres.",
    reset: "Réinitialiser les filtres",
    guardHeading: "Ce que fait AI Guard",
    proof: "Relevé de couverture",
    usesHeading: "Usages exposés",
    definition: "Définition",
    example: "Exemple illustratif",
    reflex: "Premier réflexe",
    reference: "Référence OWASP",
    scope: "La colonne AI Guard décrit le POC tel qu’il est livré, pas une promesse : seul « Couvert » signifie que l’action n’a pas lieu. Les outils cités sont libres ou open source, à titre indicatif.",
    deeper: "Explorer le relevé de couverture",
    nextTitle: "Passer des risques à vos usages.",
    nextText: "Découvrez les solutions AI Guard et choisissez votre point de départ.",
    nextLink: "Découvrir nos produits",
    footer: "xSOM AI Guard · Monitoring et cybersécurité des usages IA",
    cabinet: "Le cabinet xSOM",
    display: "Affichage",
    skip: "Aller au tableau des menaces",
  },
  en: {
    title: "AI threat glossary",
    description: "The operational glossary of AI cyber threats: typical attack, reference mitigation, open-source tools, state of the art and AI Guard coverage, filterable by use, attack surface and impact.",
    kicker: "UNDERSTAND THE RISKS",
    intro: "Find the AI threat that concerns you and discover the appropriate response: the typical attack, reference mitigation, open-source tools, and what AI Guard covers.",
    home: "Home",
    search: "Search for a threat",
    placeholder: "E.g. injection, secrets, garak, RAG…",
    sort: "Sort by",
    sorts: { category: "Category", risk: "Unsolved first", coverage: "AI Guard coverage", name: "Name (A → Z)" },
    filter: "Filter by AI use",
    all: "All uses",
    uses: { development: "Developers", workplace: "Employees", agents: "Agents", models: "Data & weights" },
    coverageFilter: "Filter by AI Guard coverage",
    coverageAll: "All",
    coverage: { yes: "Covered", partial: "Partial", no: "Not covered" },
    coverageLegend: "Covered: a shipped control blocks or holds the action on the supervised path. Partial: it detects, orchestrates a third-party tool, attests a measure or handles one facet only. Not covered: no AI Guard control.",
    category: "Category",
    categoryAll: "All categories",
    categories: {
      prompt: "Prompts & instructions",
      agents: "Agents",
      rag: "RAG",
      model: "Model & training",
      adversarial: "Adversarial ML",
      output: "Output",
      privacy: "Privacy",
      supply: "Supply chain",
      infra: "Infrastructure",
      availability: "Availability & cost",
      integrity: "Integrity & trust",
      human: "Human abuse",
      governance: "Governance",
    },
    surface: "Attack surface",
    surfaceAll: "All surfaces",
    surfaces: {
      prompt: "Prompt",
      data: "Data & context",
      model: "Model & weights",
      actions: "Actions & tools",
      people: "People",
      infra: "Infra & dependencies",
    },
    impact: "Impact",
    impactAll: "All impacts",
    impacts: {
      leak: "Data leak",
      manipulation: "Manipulated output",
      action: "Unauthorised action",
      compromise: "System compromise",
      cost: "Outage & cost",
      fraud: "Fraud",
      oversight: "Loss of oversight",
    },
    status: "State of the art",
    statusAll: "All states",
    statuses: { unsolved: "Unsolved", mitigated: "Mitigated", mixed: "Context-dependent", solved: "Controlled" },
    columns: {
      threat: "Threat",
      visual: "Preview",
      attack: "Typical attack · consequence",
      mitigation: "Reference mitigation",
      tools: "Open-source tools",
      status: "State of the art",
      guard: "AI Guard",
    },
    tableHeading: "Threat table",
    caption: "AI cyber threats: typical attack, reference mitigation, open-source tools, state of the art and AI Guard coverage. Each threat name opens its details.",
    count: "threats shown",
    countOne: "threat shown",
    of: "of",
    emptyTitle: "No threats found",
    emptyText: "Try another word or broaden the filters.",
    reset: "Reset filters",
    guardHeading: "What AI Guard does",
    proof: "Coverage record",
    usesHeading: "Exposed uses",
    definition: "Definition",
    example: "Illustrative example",
    reflex: "First step",
    reference: "OWASP reference",
    scope: "The AI Guard column describes the POC as shipped, not a promise: only “Covered” means the action does not happen. The tools listed are free or open source, for guidance only.",
    deeper: "Explore the coverage record",
    nextTitle: "Connect the risks to your AI use.",
    nextText: "Explore AI Guard solutions and choose where to start.",
    nextLink: "Discover our products",
    footer: "xSOM AI Guard · AI monitoring and cybersecurity",
    cabinet: "About xSOM",
    display: "Display",
    skip: "Skip to the threat table",
  },
} as const;
