const THREAT_VISUALS: Record<string, string> = {
  "injection-directe": "promptinjection.webp",
  "injection-de-prompt": "indirectpromptinjection.webp",
  "injection-persistante": "persistentpromptinjection.webp",
  jailbreak: "jailbreak.webp",
  "extraction-prompt-systeme": "systempromptextraction.webp",
  "detournement-de-contexte": "contexthijacking.webp",
  obfuscation: "encodingattacks.webp",
  "jailbreak-multilingue": "multilingualjailbreak.webp",
  "injection-multimodale": "multimodalpromptinjection.webp",
  "autonomie-excessive": "excessiveagency.webp",
  "injection-appel-outil": "toolcallinjection.webp",
  "depute-confus": "confuseddeputy.webp",
  "escalade-privileges-agent": "agentprivilegeescalation.webp",
  "transactions-non-autorisees": "unauthorizedtransactions.webp",
  "boucle-agent": "agentloopautomation.webp",
  "injection-inter-agents": "crossagentinjection.webp",
  "memoire-empoisonnee": "agentmemorypoisoning.webp",
  "outil-piege": "toolmisuse.webp",
  "empoisonnement-rag": "ragpoisoning.webp",
  "empoisonnement-vectoriel": "vectordbpoisoning.webp",
  "inversion-embeddings": "embeddinginversion.webp",
  "acces-rag": "retrievaldataleakage.webp",
  "fuite-inter-clients-rag": "crosstenantdataleakage.webp",
  empoisonnement: "trainingdatapoisoning.webp",
  "empoisonnement-fine-tuning": "finetunngpoisoning.webp",
  "modele-piege": "backdooredmodels.webp",
  "alteration-source-modele": "modelsourcetampering.webp",
  "modele-serialise-malveillant": "maliciousserializedmodels.webp",
  "vol-de-modele": "modeltheft.webp",
  "extraction-par-api": "modelextractionviaapi.webp",
  "inversion-de-modele": "modelinversion.webp",
  "inference-appartenance": "membershipinference.webp",
  "exemples-adverses": "Adversarial examples : evasion.webp",
  "attaque-adverse-physique": "Physical adversarial attack.webp",
  "patchs-adverses": "Adversarial patches.webp",
  "attaques-par-transfert": "Transfer attacks.webp",
  "sorties-non-maitrisees": "Improper output handling.webp",
  "injection-sql-via-llm": "SQL injection via LLM.webp",
  "injection-de-commande": "Command injection.webp",
  "xss-contenu-genere": "XSS from generated content.webp",
  "ssrf-via-agent": "SSRF through agents.webp",
  "traversee-de-chemin": "Path traversal.webp",
  "fuite-de-donnees": "dataexfiltration.webp",
  "fuite-dans-les-journaux": "Prompt leakage in logs.webp",
  "fuite-de-secrets": "Secret leakage.webp",
  "memorisation-entrainement": "traning_data_memorization.webp",
  "inference-attributs-sensibles": "Inference of sensitive attributes.webp",
  "depot-de-modeles-compromis": "Compromised model repository.webp",
  "vol-identifiants-cloud": "1bbe04ff-a4a4-4a4d-bb15-54a291735f3d.webp",
  "vol-cle-api-ia": "27e7ee88-1e74-44a4-8b3d-feddd77f39fb.webp",
  "serveur-inference-compromis": "d88ac400-305a-44f5-95e8-a7f717357bf6.webp",
  "evasion-de-conteneur": "f15577da-4305-49cf-9469-8316726ebc69.webp",
  "notebook-compromis": "07e51b5c-1c68-4fd0-bc3a-91a6c0d25af5.webp",
  "deni-de-service-modele": "88f38f75-9714-4813-837c-f88d7a827eb4.webp",
  "deni-de-portefeuille": "bda0e615-aa47-4929-a2b7-02897f894163.webp",
  "complexite-algorithmique": "5754e117-8e47-40f0-adb2-ceff7a48e7e4.webp",
  "epuisement-gpu": "7a96b229-ab10-4363-a4da-39bc3f34f578.webp",
  hallucinations: "Hallucination exploitation.webp",
  "fausses-citations": "f7146f1d-8daa-4649-b6dc-0f4998570370.webp",
  "manipulation-base-de-connaissances": "22493e98-415b-4297-a689-6597416b236f.webp",
  "phishing-augmente": "880695b6-6937-4eab-9a26-11de4ada728e.webp",
  "usurpation-deepfake": "c1aca10f-7388-4f5e-98c9-5de8bcb0ed36.webp",
  "fraude-voix-clonee": "9acfbed8-482c-4815-82dc-3d4a6f3a531c.webp",
  "decouverte-vulnerabilites": "13058bc0-dd58-42d8-9fa3-b766f9c8750a.webp",
  "shadow-ai": "14d7c130-8bda-4e5c-8e7a-691077256d65.webp",
  "provenance-modele-inconnue": "7ee97503-93de-4da1-8d8a-329c35c4fb16.webp",
  "red-teaming-insuffisant": "e83beacf-5f3b-482d-a63a-767545eadb70.webp",
  "derive-de-modele": "46a52fa3-04d0-4088-9874-f94991b43e08.webp",
};

export function visualForThreat(id: string) {
  const filename = THREAT_VISUALS[id];
  return filename ? `/threats/${encodeURIComponent(filename)}` : null;
}
